package org.koitharu.kotatsu.parsers.model

public enum class MangaParserSource(
	public val title: String,
	public val locale: String,
	public val contentType: ContentType,
	public val isBroken: Boolean,
) : MangaSource {

	ACOMICS("AComics", "ru", ContentType.COMICS, true),
	ADONISFANSUB("AdonisFansub", "tr", ContentType.MANGA, false),
	ADULT_WEBTOON("AdultWebtoon", "en", ContentType.HENTAI, false),
	ADUMANGA("AduManga", "tr", ContentType.MANGA, false),
	AFRODITSCANS("AfroditScans", "tr", ContentType.MANGA, true),
	AGSCOMICS("AgsComics", "en", ContentType.MANGA, true),
	AINZSCANS("AinzScans", "id", ContentType.MANGA, false),
	AIYUMANGASCANLATION("AiyuManhua", "es", ContentType.MANGA, true),
	ALCEASCAN("AlceaScan", "id", ContentType.MANGA, true),
	ALLHENTAI("AllHentai", "ru", ContentType.MANGA, false),
	ALLIED_FANSUB("AlliedFansub", "tr", ContentType.HENTAI, true),
	ALLMANGA("AllManga", "en", ContentType.MANGA, false),
	ALLPORN_COMIC("AllPornComic", "en", ContentType.HENTAI, false),
	ALONESCANLATOR("AloneScanlator", "pt", ContentType.MANGA, false),
	ALTAYSCANS("AltayScans", "en", ContentType.MANGA, true),
	ALTERKAISCANS("AlterkaiScans", "id", ContentType.MANGA, false),
	ALUCARDSCANS("AlucardScans", "tr", ContentType.MANGA, false),
	ANCIENTCOMICS("AncientComics", "pt", ContentType.MANGA, true),
	ANIBEL("Anibel", "be", ContentType.MANGA, true),
	ANIGLISCANS("AnigliScans", "en", ContentType.MANGA, true),
	ANIKIGA("Anikiga", "tr", ContentType.MANGA, true),
	ANIMESAMA("AnimeSama", "fr", ContentType.MANGA, true),
	ANIMEXNOVEL("AnimeXNovel", "pt", ContentType.MANGA, false),
	ANISASCANS("AnisaScans", "en", ContentType.MANGA, false),
	ANISA_MANGA("AnisaManga", "tr", ContentType.MANGA, true),
	ANSHSCANS("AnshScans", "en", ContentType.MANGA, true),
	ANTEIKUSCAN("AnteikuScan", "fr", ContentType.MANGA, true),
	ANZMANGASHD("AnzMangasHd", "es", ContentType.MANGA, false),
	APENASMAISUMYAOI("Apenasmaisum Yaoi", "pt", ContentType.HENTAI, false),
	APKOMIK("Apkomik", "id", ContentType.MANGA, false),
	APOLL_COMICS("ApollComics", "es", ContentType.MANGA, false),
	AQUAMANGA("AquaManga", "en", ContentType.MANGA, false),
	ARABSDOUJIN("ArabsDoujin", "ar", ContentType.HENTAI, true),
	ARABSHENTAI("Arabs Hentai", "ar", ContentType.HENTAI, false),
	ARABTOONS("ArabToons", "ar", ContentType.HENTAI, false),
	ARAREASCANS("ArAreaScans", "ar", ContentType.MANGA, false),
	ARAZNOVEL("ArazNovel", "tr", ContentType.MANGA, false),
	ARCANESCANS("ArcaneScans", "en", ContentType.MANGA, true),
	ARCRELIGHT("Arc-Relight", "en", ContentType.MANGA, false),
	ARCTICSCAN("ArcticScan", "pt", ContentType.MANGA, false),
	ARCURAFANSUB("ArcuraFansub", "tr", ContentType.HENTAI, false),
	AREASCANS("AreaScans", "ar", ContentType.MANGA, false),
	ARENASCANS("Arenascans", "en", ContentType.MANGA, false),
	ARGOSCOMICS("ArgosComics", "pt", ContentType.MANGA, true),
	ARMONISCANS("ArmoniScans", "tr", ContentType.MANGA, false),
	ARTESSUPREMAS("ArtesSupremas", "es", ContentType.MANGA, true),
	ARTHUR_SCAN("ArthurScan", "pt", ContentType.MANGA, false),
	ARVENSCANS("ArvenComics", "en", ContentType.MANGA, false),
	ARYASCANS("AryaScans", "en", ContentType.MANGA, false),
	ASCALONSCANS("AscalonScans", "en", ContentType.MANGA, true),
	ASEMIFANSUB("AsemiFansub", "tr", ContentType.MANGA, false),
	ASIALOTUSS("AsiaLotuss", "es", ContentType.MANGA, false),
	ASMHENTAI("AsmHentai", "type = ContentType.HENTAI", ContentType.MANGA, false),
	ASQORG("3Asq", "ar", ContentType.MANGA, false),
	ASSORTEDSCANS("AssortedScans", "en", ContentType.MANGA, false),
	ASTRALMANGA("AstralManga", "fr", ContentType.MANGA, true),
	ASTRAMES("Astrames", "fr", ContentType.MANGA, true),
	ASTRASCANS("AstraScans", "en", ContentType.MANGA, false),
	ASUPANKOMIK("AsupanKomik", "id", ContentType.MANGA, true),
	ASURASCANS("AsuraComic", "en", ContentType.MANGA, false),
	ASURASCANSGG("AsuraScansGg", "en", ContentType.MANGA, false),
	ASURASCANSTR("AsuraScansTR", "tr", ContentType.MANGA, false),
	ASURASCANS_US("AsuraScans.us", "en", ContentType.MANGA, false),
	ATEMPORAL("Atemporal", "pt", ContentType.MANGA, false),
	ATHENAMANGA("AthenaManga", "tr", ContentType.MANGA, false),
	ATIKROST("Atikrost", "tr", ContentType.MANGA, false),
	ATLANTISSCAN("AtlantisScan", "es", ContentType.MANGA, true),
	ATSUMOE("Atsu.moe", "en", ContentType.MANGA, false),
	AYATOON("AyaToon", "tr", ContentType.MANGA, false),
	AZORAMOON("Azorafly", "ar", ContentType.MANGA, false),
	BABELWUXIA("Babelwuxia", "en", ContentType.MANGA, false),
	BACAKOMIK("BacaKomik", "id", ContentType.MANGA, false),
	BAKAMAN("BakaMan", "th", ContentType.MANGA, true),
	BAKAMH("Bakamh", "zh", ContentType.MANGA, true),
	BANANASCAN("BananaScan", "fr", ContentType.MANGA, true),
	BANANASCAN_COM("BananaScan.Com", "en", ContentType.MANGA, false),
	BANANA_MANGA("BananaManga", "en", ContentType.MANGA, false),
	BAOZIMH("Baozimh", "zh", ContentType.MANGA, false),
	BARMANGA("BarManga", "es", ContentType.MANGA, false),
	BATCAVE("BatCave", "en", ContentType.COMICS, false),
	BEEHENTAI("BeeHentai", "en", ContentType.HENTAI, false),
	BEETOON("BeeToon.net", "en", ContentType.MANGA, false),
	BEGATRANSLATION("BegaTranslation", "es", ContentType.MANGA, false),
	BENTOMANGA("BentoManga", "fr", ContentType.MANGA, true),
	BENTOSCAN("BentoScan", "fr", ContentType.MANGA, true),
	BERSERKSCAN("BerserkScan", "fr", ContentType.MANGA, false),
	BESTMANHUACOM("BestManhua.com", "en", ContentType.MANGA, true),
	BEST_MANGA("BestManga", "ru", ContentType.MANGA, true),
	BEYONDTHEATARAXIA("Beyond The Ataraxia", "it", ContentType.MANGA, false),
	BIBIMANGA("BibiManga", "en", ContentType.HENTAI, true),
	BIRDMANGA("BirdManga", "en", ContentType.MANGA, true),
	BIRDTOON("BirdToon", "id", ContentType.HENTAI, true),
	BLOGTRUYEN("Blog Truyện", "vi", ContentType.MANGA, true),
	BLOGTRUYENVN("BlogTruyen.vn (Unofficial)", "vi", ContentType.MANGA, true),
	BLUELOCKSCAN("BlueLockScan", "fr", ContentType.MANGA, false),
	BLUESOLO("BlueSolo", "fr", ContentType.MANGA, true),
	BOKUGENTS("Bokugents", "es", ContentType.MANGA, false),
	BOOKMANGA("BookManga", "en", ContentType.MANGA, false),
	BORUTOEXPLORER("BorutoExplorer", "pt", ContentType.MANGA, false),
	BOYS_LOVE("BoysLove", "en", ContentType.HENTAI, true),
	BRAKEOUT("Brakeout", "es", ContentType.MANGA, true),
	BRMANGAS("BrMangas", "pt", ContentType.MANGA, true),
	BRMANGASTOP("BrMangasTop", "pt", ContentType.MANGA, false),
	BUONDUA("Buon Dua", "vi", ContentType.MANGA, false),
	BURNINGSCANS("BurningScans", "pt", ContentType.MANGA, true),
	BYMICHIBY("Bymichiby", "es", ContentType.HENTAI, false),
	CABAREDOWATAME("DessertScan", "pt", ContentType.MANGA, true),
	CAFECOMYAOI("CafecomYaoi", "pt", ContentType.HENTAI, false),
	CARTELDEMANHWAS("Cartel De Manhwas", "es", ContentType.MANGA, true),
	CATHARSISFANTASY("CatharsisFantasy", "es", ContentType.MANGA, true),
	CATHARSISWORLD("CatharsisWorld", "es", ContentType.MANGA, true),
	CAT_300("Cat300", "th", ContentType.HENTAI, false),
	CENTURYBOYS20TH("20ThCenturyBoys", "fr", ContentType.MANGA, true),
	CERISE_SCANS("CeriseScans", "pt", ContentType.MANGA, true),
	CHAINSAWMANSCAN("ChainsawManScan", "fr", ContentType.MANGA, false),
	CLONEMANGA("CloneManga", "en", ContentType.MANGA, false),
	CLOVERMANGA("CloverManga", "tr", ContentType.MANGA, true),
	CMANGA("CManga", "vi", ContentType.MANGA, false),
	COCOMIC("CoComic", "en", ContentType.HENTAI, true),
	COCORIP("Cocorip", "es", ContentType.MANGA, true),
	COFFEE_MANGA("CoffeeManga", "en", ContentType.MANGA, false),
	COLORED_MANGA("ColoredManga", "en", ContentType.MANGA, true),
	COMIC1000("Comic1000", "en", ContentType.MANGA, true),
	COMIC21("Comic21", "id", ContentType.MANGA, true),
	COMICARAB("ComicArab", "ar", ContentType.MANGA, true),
	COMICAZEN("Comicazen", "id", ContentType.MANGA, false),
	COMICEXTRA("ComicExtra", "en", ContentType.COMICS, true),
	COMICK_FUN("ComicK", "", ContentType.MANGA, false),
	COMICSVALLEY("ComicsValley", "en", ContentType.HENTAI, false),
	COMIKURO("Comikuro", "en", ContentType.MANGA, true),
	COMIX("Comix", "en", ContentType.MANGA, false),
	COMIZ("Comiz", "en", ContentType.HENTAI, false),
	COMX("Com-X", "ru", ContentType.COMICS, false),
	CONSTELLARCOMIC("ConstellarComic", "en", ContentType.HENTAI, true),
	COPYPASTESCAN("CopyPasteScan", "es", ContentType.MANGA, true),
	COSMICSCANS("CosmicScans.com", "en", ContentType.MANGA, true),
	COSMIC_SCANS("CosmicScans.id", "id", ContentType.MANGA, false),
	CREEPYSCANS("CreepyScans", "en", ContentType.MANGA, true),
	CROWSCANS("VipManga", "ar", ContentType.MANGA, true),
	CRYSTALSCAN("CrystalComics", "pt", ContentType.MANGA, false),
	CUBARI("Cubari", "type = ContentType.OTHER", ContentType.MANGA, true),
	CULTUREDWORKS("CulturedWorks", "en", ContentType.MANGA, false),
	CULTURESUBS("CultureSubs", "tr", ContentType.MANGA, true),
	CUUTRUYEN("Cứu Truyện", "vi", ContentType.MANGA, false),
	CVNSCAN("CvnScan", "pt", ContentType.HENTAI, false),
	CYPHERSCANS("CypherScans", "en", ContentType.MANGA, false),
	DAMCONUONG("Dâm Cô Nương", "vi", ContentType.MANGA, false),
	DANDADAN("Dandadan", "fr", ContentType.MANGA, false),
	DANKE("DankeFursLesen", "en", ContentType.MANGA, false),
	DAPROB("Daprob", "es", ContentType.MANGA, true),
	DARKNEBULUS("Darknebulus", "es", ContentType.MANGA, true),
	DARKSCAN("Dark-Scan", "en", ContentType.MANGA, true),
	DARK_SCANS("DarkScans", "en", ContentType.MANGA, false),
	DATGARSCANLATION("DatgarScanlation", "es", ContentType.MANGA, false),
	DAYCOMICS("DayComics", "en", ContentType.MANGA, false),
	DEATHTOLLSCANS("DeathTollScans", "en", ContentType.MANGA, false),
	DECADENCESCANS("DecadenceScans", "en", ContentType.HENTAI, false),
	DECCALSCANS("DeccalScans", "tr", ContentType.HENTAI, true),
	DEMONICSCANS("DemonicScans", "en", ContentType.MANGA, false),
	DEMONSECT("DemonSect", "pt", ContentType.MANGA, false),
	DEMONSLAYERSCAN("DemonSlayerScan", "fr", ContentType.MANGA, false),
	DESUME("Desu", "ru", ContentType.MANGA, false),
	DEXHENTAI("DexHentai", "en", ContentType.HENTAI, false),
	DIAMONDFANSUB("DiamondFansub", "tr", ContentType.MANGA, false),
	DIANXIATRADS("DianxiaTrads", "pt", ContentType.MANGA, false),
	DILARTUBE("Dilar Tube", "ar", ContentType.MANGA, false),
	DISKUSSCAN("DiskusScan", "pt", ContentType.MANGA, true),
	DIVASCANS("DivaScans", "en", ContentType.MANGA, false),
	DOCTRUYEN3Q("DocTruyen3Q", "vi", ContentType.MANGA, false),
	DOCTRUYEN5S("DocTruyen5s", "vi", ContentType.MANGA, false),
	DOJING("Dojing", "id", ContentType.HENTAI, false),
	DOMALFANSB("DomalFansub", "tr", ContentType.MANGA, true),
	DOUJIN69("Doujin69", "th", ContentType.MANGA, false),
	DOUJINDESU("DoujinDesu", "id", ContentType.MANGA, false),
	DOUJINDESURIP("DoujinDesu.click", "id", ContentType.HENTAI, false),
	DOUJINDESUUK("DoujinDesu.uk", "type = ContentType.HENTAI", ContentType.MANGA, false),
	DOUJINDESU_MANHWA("DoujinDesu Manhwa", "id", ContentType.MANGA, false),
	DOUJINKU("DoujinKu", "id", ContentType.HENTAI, false),
	DOUJINS("Doujins.lat", "es", ContentType.HENTAI, true),
	DOUJINSHELL("DoujinShell", "es", ContentType.HENTAI, false),
	DOUJINZA("Doujinza", "th", ContentType.HENTAI, false),
	DOUJIN_HENTAI_NET("DoujinHentai.net", "es", ContentType.HENTAI, false),
	DRAGONMANGA("DragonManga", "th", ContentType.HENTAI, false),
	DRAGONTEA("DragonTea", "en", ContentType.MANGA, false),
	DRAGONTRANSLATION("Dragon Translation", "es", ContentType.MANGA, true),
	DRAGONTRANSLATIONORG("DragonTranslation.org", "es", ContentType.MANGA, false),
	DRAKESCANS("DrakeComic", "en", ContentType.MANGA, true),
	DREAMSCAN("DreamScan", "pt", ContentType.MANGA, false),
	DRSTONE("DrStone", "fr", ContentType.MANGA, false),
	DTUPSCAN("DtupScan", "es", ContentType.MANGA, false),
	DUALEOTRUYEN("Dưa Leo Truyện", "vi", ContentType.MANGA, false),
	DUCKMANGA("DuckManga", "en", ContentType.HENTAI, true),
	DUNIAKOMIK("DuniaKomik", "id", ContentType.HENTAI, true),
	DUOSCANLATORS("DuoScanlators", "pt", ContentType.MANGA, false),
	DYNASTYSCANS("DynastyScans", "en", ContentType.MANGA, false),
	ECCHIDOUJIN("EcchiDoujin", "th", ContentType.HENTAI, false),
	EDOUJIN("EHentaiManga", "en", ContentType.HENTAI, false),
	EDSCANLATION("EdScanlation", "fr", ContentType.MANGA, false),
	ELARCPAGE("ElarcPage", "en", ContentType.MANGA, true),
	ELDERMANGA("Elder Manga", "tr", ContentType.MANGA, true),
	ELECEEDTURKIYE("Eleceed Türkiye", "tr", ContentType.MANGA, false),
	ELEVENSCANLATOR("ElevenScanlator", "pt", ContentType.MANGA, false),
	ELFTOON("Elftoon", "en", ContentType.MANGA, false),
	ELITEMANGA("EliteManga", "en", ContentType.MANGA, true),
	EMPERORSCAN("EmperorScan", "es", ContentType.MANGA, false),
	ENLIGNEMANGA("EnLigneManga", "fr", ContentType.MANGA, true),
	ENRYUMANGA("EnryuManga", "en", ContentType.MANGA, false),
	ENTHUNDERSCANS("EnThunderScans", "en", ContentType.MANGA, false),
	EPIKMAN("EpikMan", "tr", ContentType.MANGA, true),
	EPSILONSCAN("EpsilonScan", "fr", ContentType.HENTAI, true),
	EPSILONSOFT("EpsilonSoft", "fr", ContentType.MANGA, true),
	ERO18X("Ero18x", "", ContentType.HENTAI, false),
	EROMANHWA("EroManhwa", "", ContentType.HENTAI, true),
	EROSSCANS("ErosScans", "en", ContentType.MANGA, false),
	ESOMANGA("EsoManga", "tr", ContentType.MANGA, true),
	ETHERALRADIANCE("EtheralRadiance", "fr", ContentType.MANGA, true),
	EUPHORIASCAN("EuphoriaScan", "pt", ContentType.HENTAI, false),
	EVILMANGA("EvilManga", "cs", ContentType.HENTAI, false),
	EXHENTAI("ExHentai", "type = ContentType.HENTAI", ContentType.MANGA, false),
	EZMANGA("EzManga", "en", ContentType.MANGA, false),
	FACTMANGA("FactManga", "en", ContentType.MANGA, false),
	FAYSCANS("FayScans", "pt", ContentType.MANGA, false),
	FBSQUADS("FbSquads", "pt", ContentType.HENTAI, false),
	FECOMICC("Fecomic", "vi", ContentType.MANGA, true),
	FENIXPROJECT("FenixProject", "pt", ContentType.MANGA, false),
	FIREFORCE("FireForce", "fr", ContentType.MANGA, false),
	FIRESCANS("FireScans", "en", ContentType.MANGA, false),
	FIRSTKISSMANHUA("FirstKissManhua", "en", ContentType.MANGA, false),
	FLAMECOMICS("FlameComics", "en", ContentType.MANGA, false),
	FLARES("Fl-Ares", "ar", ContentType.MANGA, false),
	FLIXSCANS("FlixScans.net", "ar", ContentType.MANGA, true),
	FLIXSCANSORG("FlixScans.org", "en", ContentType.MANGA, true),
	FLOWERMANGA("FlowerManga", "pt", ContentType.MANGA, false),
	FMTEAM("FmTeam", "fr", ContentType.MANGA, false),
	FOXWHITE("FoxWhite", "pt", ContentType.MANGA, true),
	FRANXXMANGAS("FranxxMangas", "pt", ContentType.MANGA, true),
	FREAKCOMIC("FreakComic", "en", ContentType.MANGA, true),
	FREAKSCANS("FreakScans", "en", ContentType.MANGA, true),
	FREECOMICONLINE("FreeComicOnline", "en", ContentType.HENTAI, true),
	FREEMANGA("FreeManga", "en", ContentType.MANGA, false),
	FREEMANGATOP("FreeMangaTop", "en", ContentType.MANGA, false),
	FREEWEBTOONCOINS("FreeWebtoonCoins", "en", ContentType.MANGA, true),
	FRMANGA("FrManga", "fr", ContentType.MANGA, true),
	FRSCAN("Fr-Scan", "fr", ContentType.MANGA, true),
	FRSCANSCOM("FrScans.com", "fr", ContentType.MANGA, true),
	FURYMANGA("KingOfScans", "en", ContentType.MANGA, false),
	FURYOSOCIETY("FuryoSociety", "fr", ContentType.MANGA, false),
	FUTARI("Futari", "id", ContentType.MANGA, true),
	GAFELAND("Gafeland", "tr", ContentType.MANGA, false),
	GAIATOON("GaiaToon", "tr", ContentType.MANGA, false),
	GALAXSCANS("GalaxScanlator", "pt", ContentType.MANGA, false),
	GALINHASAMURAI("GalinhaSamurai", "pt", ContentType.MANGA, true),
	GARCIAMANGA("GarciaManga", "tr", ContentType.MANGA, false),
	GATEMANGA("GateManga", "ar", ContentType.MANGA, true),
	GDSCANS("GdScans", "en", ContentType.MANGA, false),
	GEASSCOMICS("Geass Comics", "pt", ContentType.MANGA, true),
	GEDECOMIX("GedeComix", "en", ContentType.HENTAI, false),
	GEKKOUSCANS("GekkouScans", "pt", ContentType.HENTAI, true),
	GHOSTFANSUB("GhostFansub", "tr", ContentType.MANGA, true),
	GHOSTSCAN("GhostScan", "pt", ContentType.MANGA, false),
	GISTAMISHOUSEFANSUB("GistamisHouseFansub", "es", ContentType.MANGA, false),
	GLORYMANGA("GloryManga", "tr", ContentType.MANGA, true),
	GMANGA("Gmanga", "ar", ContentType.MANGA, false),
	GOCTRUYENTRANH("Góc Truyện Tranh", "vi", ContentType.MANGA, false),
	GOCTRUYENTRANHVUI("Góc Truyện Tranh Vui", "vi", ContentType.MANGA, false),
	GOLGEBAHCESI("GolgeBahcesi", "tr", ContentType.MANGA, false),
	GOODGIRLS("GoodGirls", "en", ContentType.MANGA, true),
	GOOFFANSUB("GoofFansub", "pt", ContentType.HENTAI, true),
	GOURMETSCANS("GourmetScans", "en", ContentType.MANGA, false),
	GRABBER("Grabber", "en", ContentType.COMICS, false),
	GREEDSCANS("Greed Scans", "en", ContentType.MANGA, false),
	GREMORYMANGAS("GremoryMangas", "es", ContentType.MANGA, true),
	GRIMELEK("Grimelek", "tr", ContentType.MANGA, true),
	GTOTHEGREATSITE("GtoTheGreatSite", "it", ContentType.MANGA, false),
	GUFENGMH("Gufengmh", "zh", ContentType.MANGA, true),
	GUILDATIERDRAW("GuildaTierDraw", "pt", ContentType.MANGA, true),
	GUNCEL_MANGA("GuncelManga", "tr", ContentType.MANGA, false),
	GUYACUBARI("GuyaCubari", "en", ContentType.MANGA, false),
	HACHIRUMI("Hachirumi", "en", ContentType.HENTAI, false),
	HADESNOFANSUB("HadesNoFansub", "es", ContentType.MANGA, false),
	HAIKYUU("Haikyuu", "fr", ContentType.MANGA, false),
	HAMTRUYEN("Ham Truyện", "vi", ContentType.MANGA, true),
	HANGTRUYEN("Hang Truyện", "vi", ContentType.MANGA, false),
	HANMAN18("Hanman18", "zh", ContentType.HENTAI, false),
	HAREMSCANN("HaremScann", "es", ContentType.MANGA, true),
	HARIMANGA("HariManga", "en", ContentType.MANGA, true),
	HARMONYSCAN("HarmonyScan", "fr", ContentType.MANGA, false),
	HASTATEAM("HastaTeamDdt", "it", ContentType.MANGA, false),
	HASTATEAM_READER("HastaTeamReader", "it", ContentType.MANGA, false),
	HAYALISTIC("Hayalistic", "tr", ContentType.MANGA, false),
	HECKSCANS("HeckScans", "pt", ContentType.MANGA, false),
	HELLSPARADISESCAN("HellsParadiseScan", "fr", ContentType.MANGA, false),
	HENCHAN("Хентай-тян", "ru", ContentType.MANGA, false),
	HENSEKAI("Hensekai", "id", ContentType.HENTAI, true),
	HENTAI18VN("Hentai18VN", "vi", ContentType.MANGA, false),
	HENTAI20("Hentai20", "en", ContentType.HENTAI, false),
	HENTAI3("3Hentai", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HENTAI3Z("Hentai3z", "en", ContentType.HENTAI, true),
	HENTAI3ZCC("Hentai3z.cc", "en", ContentType.HENTAI, false),
	HENTAICROT("HentaiCrot", "id", ContentType.HENTAI, false),
	HENTAICUBE("CBHentai", "vi", ContentType.HENTAI, false),
	HENTAIENVY("HentaiEnvy", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HENTAIERA("HentaiEra", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HENTAIFORCE("HentaiForce", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HENTAIFOX("HentaiFox", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HENTAILIB("HentaiLib", "ru", ContentType.MANGA, true),
	HENTAIMANGA("HentaiManga", "en", ContentType.HENTAI, false),
	HENTAINEXUS("HentaiNexus", "en", ContentType.MANGA, false),
	HENTAIORIGINES("HentaiOrigines", "fr", ContentType.HENTAI, false),
	HENTAIREAD("HentaiRead", "en", ContentType.MANGA, false),
	HENTAIREADER("HentaiReader", "es", ContentType.HENTAI, false),
	HENTAIROX("HentaiRox", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HENTAISCANTRADVF("Hentai-Scantrad", "fr", ContentType.HENTAI, false),
	HENTAISEASON("HentaiSeason", "pt", ContentType.HENTAI, false),
	HENTAISLAYER("HentaiSlayer", "ar", ContentType.HENTAI, false),
	HENTAITECA("Hentaiteca", "pt", ContentType.HENTAI, false),
	HENTAITOKYO("HentaiTokyo", "pt", ContentType.HENTAI, false),
	HENTAIUKR("HentaiUkr", "uk", ContentType.HENTAI, false),
	HENTAIVN("HentaiVN", "vi", ContentType.MANGA, true),
	HENTAIVNBUZZ("HentaiVn.buzz", "vi", ContentType.MANGA, false),
	HENTAIVNPLUS("HentaiVN.plus", "vi", ContentType.HENTAI, false),
	HENTAIVNSU("HentaiVN.su", "vi", ContentType.MANGA, false),
	HENTAIWEBTOON("HentaiWebtoon", "en", ContentType.HENTAI, false),
	HENTAIXCOMIC("Hentai x Comic", "en", ContentType.HENTAI, false),
	HENTAIXDICKGIRL("Hentai x Dickgirl", "en", ContentType.HENTAI, false),
	HENTAIXYURI("HentaiXYuri", "en", ContentType.HENTAI, false),
	HENTAIZ("HentaiZ", "vi", ContentType.HENTAI, true),
	HENTAIZONE("HentaiZone", "fr", ContentType.HENTAI, false),
	HENTAI_4FREE("Hentai4Free", "en", ContentType.HENTAI, false),
	HENTALK("Hentalk", "en", ContentType.MANGA, false),
	HENTAMAN("Hentaman", "ar", ContentType.HENTAI, false),
	HERENSCAN("HerenScan", "es", ContentType.MANGA, false),
	HEYTOON("HeyToon", "en", ContentType.HENTAI, false),
	HHENTAIFR("H-Hentai", "fr", ContentType.HENTAI, false),
	HIJALA("Hijala", "ar", ContentType.MANGA, true),
	HIJALACOM("Hijalacom", "ar", ContentType.MANGA, false),
	HIKARISCAN("HikariScan", "pt", ContentType.MANGA, false),
	HIPERCOOL("Hipercool", "pt", ContentType.HENTAI, false),
	HIPERDEX("HiperToon", "en", ContentType.HENTAI, false),
	HITOMILA("Hitomi.La", "type = ContentType.HENTAI", ContentType.MANGA, false),
	HIVECOMIC("HiveComic", "en", ContentType.MANGA, false),
	HMANGABAT("MangaBat", "en", ContentType.MANGA, false),
	HNISCANTRAD("HniScantrad", "fr", ContentType.MANGA, false),
	HOIFANSUB("HoiFansub", "tr", ContentType.MANGA, false),
	HOLOEARTH("HoloEarth", "", ContentType.MANGA, false),
	HONEYMANGA("HoneyManga", "uk", ContentType.MANGA, false),
	HOTCOMICS("HotComics", "en", ContentType.MANGA, false),
	HOTOON("Holotoon", "id", ContentType.MANGA, false),
	HOUSEMANGAS("HouseMangas", "es", ContentType.MANGA, true),
	HOUSEOFOTAKUS("HouseOfOtakus", "es", ContentType.MANGA, true),
	HUNLIGHT("HunLight", "en", ContentType.MANGA, true),
	HUNTERSSCAN("HuntersScan", "pt", ContentType.MANGA, true),
	HUNTERSSCANEN("EnHuntersScan", "en", ContentType.MANGA, true),
	HUNTERXHUNTERSCAN("HunterXHunterScan", "fr", ContentType.MANGA, false),
	HWAGO("Hwago", "id", ContentType.MANGA, false),
	HYPERIONSCANS("SeraphManga", "tr", ContentType.MANGA, true),
	ICHIROMANGA("IchiroManga", "id", ContentType.MANGA, true),
	IKIRU("Ikiru", "id", ContentType.MANGA, false),
	ILLUSIONSCAN("IllusionScan", "pt", ContentType.HENTAI, false),
	IMHENTAI("ImHentai", "type = ContentType.HENTAI", ContentType.MANGA, false),
	IMMORTALUPDATES("ImmortalUpdates", "en", ContentType.MANGA, true),
	IMPARATORMANGA("ImparatorManga", "tr", ContentType.MANGA, true),
	IMPERIODABRITANNIA("Imp\u00e9rio da Britannia", "pt", ContentType.MANGA, false),
	IMPERIOSCANS("ImperioScans", "pt", ContentType.MANGA, true),
	INARIMANGA("InariManga", "es", ContentType.MANGA, true),
	INARIPIKAV("InariPikav", "es", ContentType.MANGA, true),
	INDO18H("Indo18h", "id", ContentType.HENTAI, true),
	INFAMOUSSCANS("InfamousScans", "en", ContentType.MANGA, true),
	INFRAFANDUB("InfraFandub", "es", ContentType.MANGA, false),
	INMANGA("InManga", "es", ContentType.MANGA, false),
	INMORALNOFANSUB("InmoralNoFansub", "es", ContentType.MANGA, true),
	INOVASCANMANGA("InovaScanManga", "fr", ContentType.MANGA, false),
	INSTAMANHWA("InstaManhwa", "en", ContentType.HENTAI, true),
	INUMANGA("InuManga", "th", ContentType.MANGA, false),
	IRISSCANLATOR("IrisScanlator", "pt", ContentType.MANGA, false),
	ISEKAISCAN("IsekaiScan.top", "en", ContentType.MANGA, false),
	ISEKAISCAN_EU("ParagonScans", "en", ContentType.MANGA, false),
	ITHINKILIKEYOU("IThinkILikeYou", "en", ContentType.COMICS, false),
	ITSYOURIGHTMANHUA("ItsYouRightManhua", "en", ContentType.MANGA, false),
	IZANAMISCANS("IzanamiScans", "id", ContentType.MANGA, false),
	JAPSCANSFR("JapScans.fr", "fr", ContentType.MANGA, true),
	JEAZTWOBLUESCANS("Jeaz Scans", "es", ContentType.MANGA, false),
	JELLYRING("Jellyring", "tr", ContentType.MANGA, true),
	JIANGZAITOON("JiangzaiToon", "tr", ContentType.HENTAI, false),
	JIMANGA("S2Manga.io", "en", ContentType.MANGA, false),
	JPMANGAS("JpMangas", "fr", ContentType.MANGA, true),
	JPSCANVF("LireScanVf.com", "fr", ContentType.MANGA, true),
	KABUSMANGA("KabusManga", "tr", ContentType.MANGA, false),
	KAGANE("Kagane", "", ContentType.MANGA, false),
	KAIJUNO8("KaijuNo8", "fr", ContentType.MANGA, true),
	KAISCANS("KaiScans", "en", ContentType.MANGA, false),
	KAKUSEIPROJECT("KakuseiProject", "pt", ContentType.MANGA, false),
	KALANGO("Kalango", "pt", ContentType.MANGA, false),
	KANZENIN("Kanzenin", "id", ContentType.HENTAI, false),
	KATAKOMIK("KataKomik", "id", ContentType.MANGA, true),
	KDTSCANS("KdtScans", "en", ContentType.MANGA, false),
	KEDI("Kedi", "tr", ContentType.MANGA, true),
	KENHUAV2SCANK("Kenhuav2Scan", "es", ContentType.MANGA, true),
	KEWNSCANS("KewnScans", "en", ContentType.MANGA, false),
	KIARA18("Kiara18", "en", ContentType.HENTAI, true),
	KINGDOMSCAN("KingdomScan", "fr", ContentType.MANGA, false),
	KINGS_MANGA("SuperDoujin", "th", ContentType.HENTAI, false),
	KIRYUU("Kiryuu", "id", ContentType.MANGA, false),
	KISHISAN("Kishisan", "id", ContentType.MANGA, true),
	KISSMANGA("KissManga", "en", ContentType.MANGA, false),
	KIUTAKU("Kiutaku", "type = ContentType.OTHER", ContentType.MANGA, false),
	KLIKMANGA("KlikManga", "id", ContentType.HENTAI, true),
	KLMANHUA("KlManhua", "id", ContentType.HENTAI, true),
	KLZ9("Klz9", "ja", ContentType.MANGA, false),
	KNIGHTNOSCANLATION("Lector KNS", "es", ContentType.MANGA, false),
	KOFISCANS("KofiScans", "id", ContentType.MANGA, false),
	KOHARU("Schale.network", "type = ContentType.HENTAI", ContentType.MANGA, false),
	KOINOBORISCAN("KoinoboriScan", "es", ContentType.MANGA, true),
	KOMBATCH("KomBatch", "id", ContentType.HENTAI, false),
	KOMIIC("Komiic", "zh", ContentType.MANGA, false),
	KOMIKAV("KomikAv", "id", ContentType.MANGA, true),
	KOMIKCAST("KomikCast", "id", ContentType.MANGA, false),
	KOMIKDEWASA("komikRemaja.icu", "id", ContentType.HENTAI, false),
	KOMIKDEWASA_ONLINE("KomikDewasa.Online", "id", ContentType.HENTAI, false),
	KOMIKGES("KomikGes", "id", ContentType.MANGA, true),
	KOMIKGO("KomikGo", "id", ContentType.HENTAI, true),
	KOMIKID("KomikId", "id", ContentType.MANGA, true),
	KOMIKINDO_CH("KomikIndo.ch", "id", ContentType.MANGA, false),
	KOMIKINDO_INFO("KomikIndo.info", "id", ContentType.HENTAI, true),
	KOMIKINDO_LIVE("Komikindo.live", "id", ContentType.HENTAI, false),
	KOMIKLAB("KomikLab", "en", ContentType.MANGA, true),
	KOMIKLOKAL("KomikLokal", "id", ContentType.MANGA, true),
	KOMIKLOKALCFD("KomikLokal.mom", "id", ContentType.HENTAI, true),
	KOMIKLOVERS("KomikLovers", "id", ContentType.MANGA, true),
	KOMIKMAMA("KomikMama", "id", ContentType.MANGA, false),
	KOMIKPIX("KomikPix", "id", ContentType.HENTAI, true),
	KOMIKPOI("KomikPoi", "id", ContentType.HENTAI, false),
	KOMIKREALM("KomikRealm", "id", ContentType.MANGA, false),
	KOMIKSAN("KomikSan", "id", ContentType.MANGA, true),
	KOMIKSAY("KomikSay", "id", ContentType.MANGA, true),
	KOMIKSIN_CO("Komiksin", "id", ContentType.MANGA, true),
	KOMIKSTATION("KomikStation", "id", ContentType.MANGA, false),
	KOMIKTAP("KomikTap", "id", ContentType.HENTAI, false),
	KOMIKU("Komiku", "id", ContentType.MANGA, false),
	KOMIKZOID("KomikzoId", "id", ContentType.MANGA, false),
	KORELISCANS("KoreliScans", "tr", ContentType.MANGA, false),
	KSGROUPSCANS("KsGroupScans", "en", ContentType.MANGA, false),
	KUMAPAGE("Kumapage", "id", ContentType.MANGA, true),
	KUMASCANS("Retsu", "en", ContentType.MANGA, false),
	KUNMANGA("KunManga", "en", ContentType.MANGA, false),
	KUROIMANGA("KuroiManga", "tr", ContentType.HENTAI, true),
	KURONEKO("Kuro Neko / vi-Hentai", "vi", ContentType.MANGA, false),
	KYUMIK("Kyumik", "id", ContentType.HENTAI, true),
	LADYESTELARSCAN("LadyEstelarScan", "pt", ContentType.MANGA, true),
	LAGOONSCANS("Lagoon Scans", "en", ContentType.MANGA, false),
	LAIDBACKSCANS("LaidBackScans", "en", ContentType.MANGA, true),
	LAMIMANGA("LamiManga", "th", ContentType.MANGA, false),
	LANGGEEK("Làng Geek", "vi", ContentType.COMICS, false),
	LAVINIAFANSUB("LaviniaFansub", "tr", ContentType.HENTAI, false),
	LECTORHENTAI("LectorHentai", "es", ContentType.HENTAI, false),
	LECTORMANGA("LectorManga", "es", ContentType.MANGA, false),
	LECTORUNITOON("LectoruniToon", "es", ContentType.MANGA, true),
	LECTORUNM("Lectorunm.life", "es", ContentType.MANGA, true),
	LEGACY_SCANS("LegacyScans", "fr", ContentType.MANGA, true),
	LEGENDSCANLATIONS("LegendScanlations", "es", ContentType.MANGA, false),
	LEGIONSCANS("CerberusSeries", "es", ContentType.MANGA, true),
	LEITORDEMANGA("LeitorDeManga", "pt", ContentType.MANGA, false),
	LEITORKAMISAMA("LeitorKamisama", "pt", ContentType.MANGA, false),
	LEKMANGACOM("LekMangaCom", "ar", ContentType.MANGA, false),
	LEKMANGAORG("LekManga.org", "ar", ContentType.MANGA, false),
	LELMANGA("LelManga", "fr", ContentType.MANGA, false),
	LELSCANVF("LelScanFr", "fr", ContentType.MANGA, false),
	LEPOYTL("Lepoytl", "id", ContentType.MANGA, false),
	LER999("Ler999", "pt", ContentType.MANGA, false),
	LERHENTAI("LerHentai", "pt", ContentType.HENTAI, false),
	LERMANGA("LerManga", "pt", ContentType.MANGA, true),
	LERMANGAONLINE("LerMangaOnline", "pt", ContentType.MANGA, true),
	LERMANGAS("Lermangas", "pt", ContentType.MANGA, false),
	LERYAOI("LerYaoi", "pt", ContentType.HENTAI, false),
	LEVIATANSCANS("LsComic", "en", ContentType.MANGA, true),
	LHTRANSLATION("LhTranslation", "en", ContentType.MANGA, false),
	LIANSCANS("LianScans", "id", ContentType.HENTAI, false),
	LICHMANGAS("LichMangas", "pt", ContentType.MANGA, false),
	LICHSUBS("LichSubs", "tr", ContentType.MANGA, true),
	LIKEMANGA("LikeManga", "en", ContentType.MANGA, false),
	LIKEMANGAIN("LikeManga.in", "en", ContentType.MANGA, true),
	LIKEMANGANET("Like-Manga.net", "ar", ContentType.MANGA, false),
	LILYMANGA("LilyManga", "en", ContentType.HENTAI, false),
	LILYUMFANSUB("LilyumFansub", "tr", ContentType.MANGA, false),
	LIMBOSCAN("LimboScan", "pt", ContentType.MANGA, false),
	LIMITEDTIMEPOJECT("LimitedTimePoject", "pt", ContentType.MANGA, false),
	LINEWEBTOONS_DE("LineWebtoons German", "de", ContentType.MANGA, true),
	LINEWEBTOONS_EN("LineWebtoons English", "en", ContentType.MANGA, true),
	LINEWEBTOONS_ES("LineWebtoons Spanish", "es", ContentType.MANGA, true),
	LINEWEBTOONS_FR("LineWebtoons French", "fr", ContentType.MANGA, true),
	LINEWEBTOONS_ID("LineWebtoons Indonesian", "id", ContentType.MANGA, true),
	LINEWEBTOONS_TH("LineWebtoons Thai", "th", ContentType.MANGA, true),
	LINEWEBTOONS_ZH("LineWebtoons Chinese", "zh", ContentType.MANGA, true),
	LINKSTARTSCAN("LinkStartScan", "pt", ContentType.MANGA, true),
	LIRESCAN("LireScan", "fr", ContentType.MANGA, true),
	LKSCANLATION("LkScanlation", "es", ContentType.MANGA, true),
	LMTOS("Lmtos", "es", ContentType.MANGA, true),
	LOLICONMOBI("LoliconMobi", "en", ContentType.HENTAI, true),
	LONERTL("LonerTranslations", "ar", ContentType.MANGA, false),
	LUACOMIC_COM("Lua Scans", "en", ContentType.MANGA, true),
	LUFFYMANGA("LuffyManga", "en", ContentType.MANGA, true),
	LUGNICASCANS("LugnicaScans", "fr", ContentType.MANGA, true),
	LUMINOUSSCANS("RadiantScans", "en", ContentType.MANGA, true),
	LUMOSKOMIK("LumosKomik", "id", ContentType.MANGA, false),
	LUNARANIME("Lunar Manga", "", ContentType.MANGA, false),
	LUNARHENTAI("GloryScans", "fr", ContentType.MANGA, true),
	LUNARSCAN("LunarrScan.com", "pt", ContentType.MANGA, true),
	LUNARSCANS("LunarScans", "fr", ContentType.MANGA, true),
	LUNAR_SCAN("LunarScan.org", "en", ContentType.HENTAI, false),
	LUNASCANS("LunaScans", "tr", ContentType.HENTAI, false),
	LUPITEAM("LupiTeam", "it", ContentType.MANGA, false),
	LUVYAA("Luvyaa", "id", ContentType.HENTAI, false),
	LUXMANGA("LuxManga", "en", ContentType.MANGA, true),
	LXMANGA("LXManga", "vi", ContentType.MANGA, false),
	MADARADEX("MadaraDex", "en", ContentType.HENTAI, false),
	MADARASCANS("Madara Scans", "en", ContentType.MANGA, false),
	MAFIAMANGA("MafiaManga", "th", ContentType.MANGA, false),
	MAGERIN("Magerin", "id", ContentType.MANGA, true),
	MAGUSMANGA("MagusToon", "en", ContentType.MANGA, false),
	MAHOUSHOUJOBU("MahouShoujobu", "", ContentType.MANGA, false),
	MAIDSCAN("MaidScan", "pt", ContentType.MANGA, false),
	MAIDSECRET("MaidSecret", "pt", ContentType.MANGA, false),
	MAID_ID("MaidId", "id", ContentType.MANGA, false),
	MAKIMAAAAA("Makimaaaaa", "th", ContentType.MANGA, false),
	MANGA1001("Manga1001", "en", ContentType.MANGA, true),
	MANGA168("Manga168", "th", ContentType.HENTAI, false),
	MANGA18("Manga18", "en", ContentType.HENTAI, false),
	MANGA18FX("Manga18Fx", "", ContentType.HENTAI, false),
	MANGA18H("Manga18h", "en", ContentType.HENTAI, true),
	MANGA18X("Manga18x", "en", ContentType.HENTAI, false),
	MANGA18XYZ("Manga18.xyz", "en", ContentType.HENTAI, true),
	MANGA1K("Manga1k", "en", ContentType.HENTAI, true),
	MANGA1ST("Manga1st", "en", ContentType.MANGA, false),
	MANGA4LIFE("Manga4Life", "en", ContentType.MANGA, true),
	MANGA68("Manga68", "en", ContentType.MANGA, true),
	MANGA689("Manga689", "th", ContentType.MANGA, false),
	MANGAACTION("MangaAction", "en", ContentType.MANGA, true),
	MANGAAILAND("MangaAiLand", "ar", ContentType.MANGA, false),
	MANGAATREND("MangaAtrend", "ar", ContentType.MANGA, false),
	MANGAAY("MangaAy", "tr", ContentType.MANGA, false),
	MANGABALL_AR("Manga Ball (Arabic)", "ar", ContentType.MANGA, false),
	MANGABALL_BG("Manga Ball (Bulgarian)", "bg", ContentType.MANGA, false),
	MANGABALL_BN("Manga Ball (Bengali)", "bn", ContentType.MANGA, false),
	MANGABALL_CA("Manga Ball (Catalan)", "ca", ContentType.MANGA, false),
	MANGABALL_CS("Manga Ball (Czech)", "cs", ContentType.MANGA, false),
	MANGABALL_DA("Manga Ball (Danish)", "da", ContentType.MANGA, false),
	MANGABALL_DE("Manga Ball (German)", "de", ContentType.MANGA, false),
	MANGABALL_EL("Manga Ball (Greek)", "el", ContentType.MANGA, false),
	MANGABALL_EN("Manga Ball (English)", "en", ContentType.MANGA, false),
	MANGABALL_ES("Manga Ball (Spanish)", "es", ContentType.MANGA, false),
	MANGABALL_FA("Manga Ball (Persian)", "fa", ContentType.MANGA, false),
	MANGABALL_FI("Manga Ball (Finnish)", "fi", ContentType.MANGA, false),
	MANGABALL_FR("Manga Ball (French)", "fr", ContentType.MANGA, false),
	MANGABALL_HE("Manga Ball (Hebrew)", "he", ContentType.MANGA, false),
	MANGABALL_HI("Manga Ball (Hindi)", "hi", ContentType.MANGA, false),
	MANGABALL_HU("Manga Ball (Hungarian)", "hu", ContentType.MANGA, false),
	MANGABALL_ID("Manga Ball (Indonesian)", "id", ContentType.MANGA, false),
	MANGABALL_IS("Manga Ball (Icelandic)", "is", ContentType.MANGA, false),
	MANGABALL_IT("Manga Ball (Italian)", "it", ContentType.MANGA, false),
	MANGABALL_JA("Manga Ball (Japanese)", "ja", ContentType.MANGA, false),
	MANGABALL_KN("Manga Ball (Kannada)", "kn", ContentType.MANGA, false),
	MANGABALL_KO("Manga Ball (Korean)", "ko", ContentType.MANGA, false),
	MANGABALL_ML("Manga Ball (Malayalam)", "ml", ContentType.MANGA, false),
	MANGABALL_MS("Manga Ball (Malay)", "ms", ContentType.MANGA, false),
	MANGABALL_NE("Manga Ball (Nepali)", "ne", ContentType.MANGA, false),
	MANGABALL_NL("Manga Ball (Dutch)", "nl", ContentType.MANGA, false),
	MANGABALL_NO("Manga Ball (Norwegian)", "no", ContentType.MANGA, false),
	MANGABALL_PL("Manga Ball (Polish)", "pl", ContentType.MANGA, false),
	MANGABALL_PTBR("Manga Ball (Portuguese)", "pt", ContentType.MANGA, false),
	MANGABALL_RO("Manga Ball (Romanian)", "ro", ContentType.MANGA, false),
	MANGABALL_RU("Manga Ball (Russian)", "ru", ContentType.MANGA, false),
	MANGABALL_SK("Manga Ball (Slovak)", "sk", ContentType.MANGA, false),
	MANGABALL_SL("Manga Ball (Slovenian)", "sl", ContentType.MANGA, false),
	MANGABALL_SQ("Manga Ball (Albanian)", "sq", ContentType.MANGA, false),
	MANGABALL_SR("Manga Ball (Serbian)", "sr", ContentType.MANGA, false),
	MANGABALL_SV("Manga Ball (Swedish)", "sv", ContentType.MANGA, false),
	MANGABALL_TA("Manga Ball (Tamil)", "ta", ContentType.MANGA, false),
	MANGABALL_TH("Manga Ball (Thai)", "th", ContentType.MANGA, false),
	MANGABALL_TR("Manga Ball (Turkish)", "tr", ContentType.MANGA, false),
	MANGABALL_UK("Manga Ball (Ukrainian)", "uk", ContentType.MANGA, false),
	MANGABALL_VI("Manga Ball (Vietnamese)", "vi", ContentType.MANGA, false),
	MANGABALL_ZH("Manga Ball (Chinese)", "zh", ContentType.MANGA, false),
	MANGABEE("MangaBee", "en", ContentType.HENTAI, false),
	MANGABOB("MangaBob", "en", ContentType.MANGA, true),
	MANGABR("MangaBr", "pt", ContentType.MANGA, true),
	MANGABUDDY("MangaBuddy", "en", ContentType.MANGA, true),
	MANGABUFF("MangaBuff", "ru", ContentType.MANGA, false),
	MANGACHAN("Манга-тян", "ru", ContentType.MANGA, false),
	MANGACIM("Mangacim", "tr", ContentType.MANGA, true),
	MANGACIX("Mangacix", "tr", ContentType.MANGA, false),
	MANGACLASH("ToonClash", "en", ContentType.MANGA, false),
	MANGACLOUD("MangaCloud", "en", ContentType.MANGA, false),
	MANGACRAZY("MangaCrazy", "", ContentType.HENTAI, false),
	MANGACULTIVATOR("MangaCultivator", "en", ContentType.MANGA, true),
	MANGACUTE("MangaCute", "en", ContentType.MANGA, true),
	MANGADASS("MangaDass", "en", ContentType.HENTAI, false),
	MANGADEEMAK("MangaDeemak", "th", ContentType.MANGA, false),
	MANGADEX("MangaDex", "", ContentType.MANGA, false),
	MANGADNA("MangaDna", "en", ContentType.HENTAI, false),
	MANGADOOR("MangaDoor", "es", ContentType.MANGA, true),
	MANGADOP("MangaDop", "id", ContentType.HENTAI, false),
	MANGADOTNET("Mangadotnet", "en", ContentType.MANGA, false),
	MANGAECLIPSE("MangaEclipse", "en", ContentType.MANGA, false),
	MANGAEFENDISI("MangaEfendisi", "tr", ContentType.MANGA, false),
	MANGAEFFECT("MangaEffect", "en", ContentType.MANGA, true),
	MANGAESP("MangaEsp", "es", ContentType.MANGA, true),
	MANGAFASTNET("MangaFast.net", "en", ContentType.MANGA, false),
	MANGAFENXI("MangaFenxi", "ja", ContentType.MANGA, true),
	MANGAFIRE_EN("MangaFire (English)", "en", ContentType.MANGA, false),
	MANGAFIRE_ES("MangaFire (Spanish)", "es", ContentType.MANGA, false),
	MANGAFIRE_ESLA("MangaFire Spanish (Latin)", "es", ContentType.MANGA, false),
	MANGAFIRE_FR("MangaFire (French)", "fr", ContentType.MANGA, false),
	MANGAFIRE_JA("MangaFire (Japanese)", "ja", ContentType.MANGA, false),
	MANGAFIRE_PT("MangaFire (Portuguese)", "pt", ContentType.MANGA, false),
	MANGAFIRE_PTBR("MangaFire Portuguese (Brazil)", "pt", ContentType.MANGA, false),
	MANGAFLAME("MangaFlame", "ar", ContentType.MANGA, false),
	MANGAFOREST("MangaForest", "en", ContentType.MANGA, false),
	MANGAFORFREE("MangaForFree", "en", ContentType.HENTAI, false),
	MANGAFOXFULL("MangaFoxFull", "en", ContentType.MANGA, false),
	MANGAFR("MangaFr", "fr", ContentType.MANGA, false),
	MANGAFREAK("MangaFreak", "en", ContentType.MANGA, false),
	MANGAGALAXY("MangaGalaxy", "en", ContentType.MANGA, true),
	MANGAGEKO("MangaGeko", "en", ContentType.MANGA, false),
	MANGAGEZGINI("MangaGezgini", "tr", ContentType.MANGA, false),
	MANGAGG("MangaGg", "en", ContentType.MANGA, false),
	MANGAGO("Mangago", "en", ContentType.MANGA, false),
	MANGAGOJO("MangaGojo", "en", ContentType.MANGA, false),
	MANGAHALL("MangaHolic", "en", ContentType.HENTAI, true),
	MANGAHAUS("MangaHaus", "de", ContentType.MANGA, false),
	MANGAHENTAI("MangaHentai", "en", ContentType.HENTAI, false),
	MANGAHONA("MangaHona", "pl", ContentType.MANGA, false),
	MANGAHUB("MangaHub", "fr", ContentType.HENTAI, false),
	MANGAHUB_IO("MangaHubIO", "en", ContentType.MANGA, true),
	MANGAHUB_LINK("MangaHub.link", "ar", ContentType.HENTAI, false),
	MANGAID("MangaId", "id", ContentType.MANGA, true),
	MANGAINUA("MANGA/in/UA", "uk", ContentType.MANGA, false),
	MANGAIRO("MangaIro", "en", ContentType.MANGA, true),
	MANGAITALIA("MangaItalia", "it", ContentType.MANGA, false),
	MANGAJINX("MangaJinx", "en", ContentType.MANGA, false),
	MANGAJP("MangaJp", "ja", ContentType.MANGA, false),
	MANGAKAKALOT("Mangakakalot.gg", "en", ContentType.MANGA, false),
	MANGAKAKALOTTV("Mangakakalot.tv", "en", ContentType.MANGA, false),
	MANGAKATANA("MangaKatana", "en", ContentType.MANGA, false),
	MANGAKAWAII("MangaKawaii Fr", "fr", ContentType.MANGA, false),
	MANGAKAWAII_EN("MangaKawaii En", "en", ContentType.MANGA, false),
	MANGAKAZANI("MangaKazani", "tr", ContentType.MANGA, true),
	MANGAKIMI("MangaKimi", "th", ContentType.MANGA, false),
	MANGAKINGS("MangaKings", "tr", ContentType.MANGA, false),
	MANGAKIO("MangaKIO", "en", ContentType.MANGA, false),
	MANGAKISS("MangaKiss", "en", ContentType.MANGA, false),
	MANGAKITA("MangaKita", "id", ContentType.MANGA, false),
	MANGAKOINU("MangaKoinu", "ja", ContentType.MANGA, false),
	MANGAKOLEJI("MangaKoleji", "tr", ContentType.MANGA, false),
	MANGAKOMA01("MangaKoma01", "ja", ContentType.MANGA, false),
	MANGAKYO("MangaKyo", "id", ContentType.MANGA, true),
	MANGALAND("MangaLand", "es", ContentType.HENTAI, false),
	MANGALC("MangaLc", "th", ContentType.MANGA, false),
	MANGALEK("LekManga", "ar", ContentType.MANGA, false),
	MANGALEKO("Manga-Leko.org", "ar", ContentType.MANGA, false),
	MANGALESEN("MangaLesen", "de", ContentType.MANGA, true),
	MANGALEVELING("MangaLeveling", "en", ContentType.MANGA, false),
	MANGALIB("MangaLib", "ru", ContentType.MANGA, false),
	MANGALINKNET("Link-Manga.com", "ar", ContentType.MANGA, false),
	MANGALIONZ("Manga-Lionz", "ar", ContentType.MANGA, false),
	MANGALIVRE("Manga Livre", "pt", ContentType.MANGA, false),
	MANGAMAMMY("MangaMammy", "ru", ContentType.MANGA, false),
	MANGAMANA("MangaMana", "fr", ContentType.MANGA, false),
	MANGAMANIACS("MangaManiacs", "en", ContentType.HENTAI, false),
	MANGAMATE("MangaMate", "ja", ContentType.MANGA, false),
	MANGAMOINS("MangaMoins", "fr", ContentType.MANGA, false),
	MANGAMOONS("MangaMoons", "th", ContentType.MANGA, true),
	MANGAMUNDODRAMA("InmortalScan", "es", ContentType.MANGA, false),
	MANGANANQUIM("MangaNanquim", "pt", ContentType.MANGA, true),
	MANGANATO("Manganato", "en", ContentType.MANGA, true),
	MANGANELO_COM("MangaNelo.com", "en", ContentType.MANGA, true),
	MANGANINJA("MangaNinja", "pt", ContentType.MANGA, false),
	MANGANOON("MangaNoon", "ar", ContentType.MANGA, true),
	MANGAOKU("Mangaoku", "tr", ContentType.MANGA, true),
	MANGAOKUSANA("MangaOkusana", "tr", ContentType.MANGA, true),
	MANGAOKUTR("MangaOkuTr", "tr", ContentType.MANGA, false),
	MANGAONELOVE("MangaOneLove", "ru", ContentType.MANGA, false),
	MANGAONI("MangaOni", "es", ContentType.MANGA, false),
	MANGAONLINE("MangaOnline.biz", "pt", ContentType.MANGA, false),
	MANGAONLINETEAM("MangaOnlineTeam", "en", ContentType.MANGA, false),
	MANGAONLINE_BLOG("MangaOnline", "pt", ContentType.MANGA, false),
	MANGAOWL("MangaOwl.to", "en", ContentType.MANGA, true),
	MANGAOWLBLOG("MangaOwlnet.com", "en", ContentType.MANGA, true),
	MANGAOWL_IO("MangaOwl.io", "en", ContentType.MANGA, false),
	MANGAOWL_ONE("MangaOwl.one", "en", ContentType.HENTAI, true),
	MANGAOWL_US("MangaOwlYaoi", "en", ContentType.HENTAI, true),
	MANGAPARK("MangaPark", "", ContentType.MANGA, true),
	MANGAPEAK("MangaPeak", "ar", ContentType.MANGA, true),
	MANGAPILL("MangaPill", "en", ContentType.MANGA, false),
	MANGAPLUSPARSER_DE("MANGA Plus German", "de", ContentType.MANGA, false),
	MANGAPLUSPARSER_EN("MANGA Plus English", "en", ContentType.MANGA, false),
	MANGAPLUSPARSER_ES("MANGA Plus Spanish", "es", ContentType.MANGA, false),
	MANGAPLUSPARSER_FR("MANGA Plus French", "fr", ContentType.MANGA, false),
	MANGAPLUSPARSER_ID("MANGA Plus Indonesian", "id", ContentType.MANGA, false),
	MANGAPLUSPARSER_PTBR("MANGA Plus Portuguese (Brazil)", "pt", ContentType.MANGA, false),
	MANGAPLUSPARSER_RU("MANGA Plus Russian", "ru", ContentType.MANGA, false),
	MANGAPLUSPARSER_TH("MANGA Plus Thai", "th", ContentType.MANGA, false),
	MANGAPLUSPARSER_VI("MANGA Plus Vietnamese", "vi", ContentType.MANGA, false),
	MANGAPUMA("MangaPuma", "en", ContentType.MANGA, true),
	MANGAPURE("MangaPure", "en", ContentType.MANGA, true),
	MANGARAW("MangaRaw", "ja", ContentType.MANGA, false),
	MANGARBIC("MangaArabic", "ar", ContentType.MANGA, true),
	MANGAREAD("MangaRead", "en", ContentType.MANGA, false),
	MANGAREADCO("MangaRead.co", "en", ContentType.MANGA, false),
	MANGAREADERTO("MangaReader.To", "", ContentType.MANGA, false),
	MANGAROCK("MangaRock", "en", ContentType.MANGA, false),
	MANGAROCKTEAM("MangaRock.team", "en", ContentType.MANGA, false),
	MANGAROLLS("MangaRolls", "en", ContentType.MANGA, false),
	MANGAROSE("MangaRose", "ar", ContentType.MANGA, false),
	MANGAROSIE("Toon69", "en", ContentType.MANGA, true),
	MANGARUBY("MangaRuby", "en", ContentType.MANGA, true),
	MANGARUHU("MangaRuhu", "tr", ContentType.MANGA, true),
	MANGARYU("MangaRyu", "en", ContentType.HENTAI, true),
	MANGASCHAN("MangasChan", "pt", ContentType.MANGA, true),
	MANGASECT("MangaSect", "en", ContentType.MANGA, false),
	MANGASEE("MangaSee", "en", ContentType.MANGA, true),
	MANGASEHRI("MangaSehri.com", "tr", ContentType.MANGA, false),
	MANGASEHRINET("MangaSehri.net", "tr", ContentType.MANGA, false),
	MANGASHIINA("MangaMukai.com", "es", ContentType.MANGA, false),
	MANGASHIRO("MangaShiro", "id", ContentType.MANGA, true),
	MANGASIGINAGI("MangaSiginagi", "tr", ContentType.MANGA, true),
	MANGASNOSEKAI("MangasNoSekai", "es", ContentType.MANGA, false),
	MANGASONLINE("MangasOnline", "pt", ContentType.MANGA, true),
	MANGASORIGINES("MangasOrigines.fr", "fr", ContentType.MANGA, false),
	MANGASORIGINESUNOFFICIAL("CrunchyScan", "fr", ContentType.MANGA, true),
	MANGASOUL("MangaSoul", "ar", ContentType.MANGA, false),
	MANGASPARK("Manga-Spark", "ar", ContentType.MANGA, true),
	MANGASSCANS("MangasScans", "fr", ContentType.MANGA, false),
	MANGASTARZ("Manga-Starz", "ar", ContentType.MANGA, false),
	MANGASTORM("MangaStorm", "ar", ContentType.MANGA, true),
	MANGASUSHI("MangaSushi", "en", ContentType.MANGA, false),
	MANGASUSUKU("MangaSusuku", "id", ContentType.HENTAI, false),
	MANGASWAT("Manga Swat", "ar", ContentType.MANGA, false),
	MANGASY("Mangasy", "en", ContentType.MANGA, true),
	MANGATALE("MangaTale", "id", ContentType.MANGA, true),
	MANGATARO("Mangataro", "en", ContentType.MANGA, false),
	MANGATELLERS("Mangatellers", "en", ContentType.MANGA, false),
	MANGATERRA("MangaTerra", "pt", ContentType.MANGA, false),
	MANGATILKISI("MangaTilkisi", "tr", ContentType.MANGA, false),
	MANGATIME("MangaTime", "ar", ContentType.MANGA, true),
	MANGATOP("MangaTop", "", ContentType.HENTAI, true),
	MANGATOWN("MangaTown", "en", ContentType.MANGA, false),
	MANGATR("MangaTr", "tr", ContentType.MANGA, false),
	MANGATV("MangaTv", "es", ContentType.MANGA, false),
	MANGATXUNOFFICIAL("MangaEmpress", "en", ContentType.MANGA, false),
	MANGATX_CC("MangaTx.cc", "en", ContentType.MANGA, false),
	MANGATX_GG("MangaTx.gg", "en", ContentType.MANGA, false),
	MANGATYRANT("MangaTyrant", "en", ContentType.MANGA, false),
	MANGAUS("Mangaus", "en", ContentType.MANGA, true),
	MANGAWEEBS("MangaWeebs", "en", ContentType.MANGA, false),
	MANGAWORLD("MangaWorld", "it", ContentType.MANGA, false),
	MANGAWORLDADULT("MangaWorldAdult", "it", ContentType.MANGA, false),
	MANGAWOW("MangaWow", "tr", ContentType.MANGA, false),
	MANGAWT("MangaWt.com", "tr", ContentType.MANGA, false),
	MANGAWT_NET("MangaWt.net", "tr", ContentType.MANGA, false),
	MANGAXICO("MangaXico", "es", ContentType.HENTAI, false),
	MANGAXYZ("MangaXyz", "en", ContentType.MANGA, true),
	MANGAYARO("MangaYaro", "id", ContentType.MANGA, true),
	MANGAZAVR("Mangazavr", "ru", ContentType.HENTAI, false),
	MANGAZIN("MangaZin", "en", ContentType.MANGA, false),
	MANGAZODIAC("MangaZodiac", "vi", ContentType.MANGA, true),
	MANGA_CRAB("MangaCrab", "es", ContentType.MANGA, false),
	MANGA_DENIZI("MangaDenizi", "tr", ContentType.MANGA, false),
	MANGA_DISTRICT("MangaDistrict", "en", ContentType.HENTAI, false),
	MANGA_KOMI("MangaKomi", "en", ContentType.MANGA, false),
	MANGA_MANHUA("MangaManhua", "en", ContentType.MANGA, false),
	MANGA_QUEEN("MangaQueen", "en", ContentType.MANGA, true),
	MANGA_SCAN("MangaScan", "fr", ContentType.MANGA, true),
	MANGA_SCANTRAD("MangaScantrad.io", "fr", ContentType.MANGA, false),
	MANGA_WTF("MangaWtf", "ru", ContentType.MANGA, false),
	MANHASTRO("Manhastro", "pt", ContentType.MANGA, false),
	MANHATIC("Manhatic", "ar", ContentType.HENTAI, false),
	MANHATOK("ManhaTok", "ar", ContentType.MANGA, false),
	MANHUABUG("ManhuaBug", "th", ContentType.MANGA, false),
	MANHUAES("ManhuaEs", "en", ContentType.MANGA, false),
	MANHUAFAST("ManhuaFast", "en", ContentType.MANGA, false),
	MANHUAGA("ManhuaGa", "en", ContentType.MANGA, false),
	MANHUAGOLD("ManhuaGold", "en", ContentType.MANGA, false),
	MANHUAGUI("Manhuagui", "zh", ContentType.MANGA, false),
	MANHUAHOT("ManhuaHot", "en", ContentType.MANGA, false),
	MANHUAKEY("ManhuaKey", "th", ContentType.MANGA, true),
	MANHUAMANHWA("ManhuaManhwa", "en", ContentType.MANGA, false),
	MANHUAPLUS("ManhuaPlus", "en", ContentType.MANGA, false),
	MANHUAPLUSORG("ManhuaPlus.org", "en", ContentType.MANGA, false),
	MANHUASCAN("kaliscan.io", "en", ContentType.MANGA, false),
	MANHUASCANUS("ManhuaScan.Us", "en", ContentType.HENTAI, false),
	MANHUASY("ManhuaSy", "en", ContentType.MANGA, true),
	MANHUAUS("ManhuaUs", "en", ContentType.MANGA, false),
	MANHUAUSS("Manhuauss", "en", ContentType.MANGA, false),
	MANHUAZONE("ManhuaZone", "en", ContentType.MANGA, false),
	MANHUAZONGHE("ManhuaZonghe", "en", ContentType.MANGA, false),
	MANHWA18("Manhwa18.net", "en", ContentType.MANGA, false),
	MANHWA18APP("Manhwa18.app", "en", ContentType.HENTAI, true),
	MANHWA18CC("Manhwa18.cc", "", ContentType.HENTAI, false),
	MANHWA18COM("Manhwa18.com", "en", ContentType.MANGA, false),
	MANHWA18ORG("Manhwa18.org", "en", ContentType.HENTAI, false),
	MANHWA210("Manhwa210", "type = ContentType.MANHWA", ContentType.MANGA, false),
	MANHWA68("Manhwa68", "en", ContentType.HENTAI, false),
	MANHWABREAKUP("ManhwaBreakup", "th", ContentType.MANGA, false),
	MANHWACLAN("ManhwaClan", "en", ContentType.MANGA, false),
	MANHWADEN("ManhwaDen", "en", ContentType.HENTAI, false),
	MANHWADESU("ManhwaDesu", "id", ContentType.HENTAI, false),
	MANHWAFREAKE("ManhwaFreake", "en", ContentType.MANGA, false),
	MANHWAFULL("ManhwaFull", "en", ContentType.MANGA, false),
	MANHWAHENTAI("ManhwaHentai", "en", ContentType.HENTAI, false),
	MANHWAHENTAITO("ManhwaHentai.to", "en", ContentType.HENTAI, false),
	MANHWAHUB("ManhwaHub", "id", ContentType.HENTAI, false),
	MANHWAINDO("ManhwaIndo", "id", ContentType.MANGA, false),
	MANHWAINDOICU("KomikCinta", "id", ContentType.HENTAI, false),
	MANHWAKU("Manhwaku", "id", ContentType.MANGA, false),
	MANHWALAND("ManhwaLand.vip", "id", ContentType.HENTAI, false),
	MANHWALAND_INK("ManhwaLand.ink", "id", ContentType.HENTAI, false),
	MANHWALATINO("ManhwaLatino", "es", ContentType.MANGA, false),
	MANHWALIST("ManhwaList", "id", ContentType.MANGA, true),
	MANHWALIST_ORG("ManhwaList.org", "id", ContentType.MANGA, false),
	MANHWALOVER("ManhwaLover", "en", ContentType.HENTAI, true),
	MANHWAMANHUA("ManhwaManhua", "en", ContentType.MANGA, false),
	MANHWANEW("ManhwaNew", "en", ContentType.MANGA, true),
	MANHWAONLINE("ManhwaOnline", "es", ContentType.MANGA, false),
	MANHWAPLUS("ManhwaPlus", "id", ContentType.HENTAI, true),
	MANHWARAW("ManhwaRaw", "", ContentType.HENTAI, false),
	MANHWARAW_COM("ManhwaRaw.com", "en", ContentType.HENTAI, false),
	MANHWASCO("ManhwaSco", "en", ContentType.MANGA, false),
	MANHWASMEN("ManhwasMen", "en", ContentType.MANGA, false),
	MANHWAS_ES("Manhwas.es", "es", ContentType.HENTAI, false),
	MANHWATOON("ManhwaToon", "en", ContentType.HENTAI, false),
	MANHWATOP("ManhwaTop", "en", ContentType.MANGA, false),
	MANHWAX("ManhwaX", "en", ContentType.HENTAI, false),
	MANHWAZ("ManhwaZ", "en", ContentType.MANGA, false),
	MANHWA_ES("Manhwa-Es", "es", ContentType.MANGA, false),
	MANHWA_FREAK("ManhwaFreak", "en", ContentType.MANGA, true),
	MANJANOON("Manjanoon", "ar", ContentType.MANGA, false),
	MANJANOON_EN("NoonScan.net", "en", ContentType.MANGA, true),
	MANTRAZSCAN("MantrazScan", "es", ContentType.MANGA, false),
	MANWE("Manwe", "tr", ContentType.MANGA, true),
	MANYCOMIC("ManyComic", "en", ContentType.HENTAI, true),
	MANYTOON("ManyToon", "en", ContentType.HENTAI, false),
	MANYTOONME("ManyToon.me", "en", ContentType.HENTAI, false),
	MANYTOON_CLUB("ManyToon.club", "", ContentType.HENTAI, false),
	MARMOTA("Marmota", "es", ContentType.COMICS, false),
	MASHLESCAN("MashleScan", "fr", ContentType.MANGA, false),
	MASTERKOMIK("Tenshi", "id", ContentType.MANGA, true),
	MAXGSSCAN("MaxgsScan", "pt", ContentType.MANGA, true),
	MEDIOCRETOONS("MediocreToons", "pt", ContentType.MANGA, false),
	MEDUSASCANS("Medusascans", "id", ContentType.HENTAI, false),
	MEHENTAIVN("MeHentaiVN", "vi", ContentType.HENTAI, false),
	MENUDO_FANSUB("Menudo Fansub", "es", ContentType.MANGA, false),
	MERLINSCANS("MerlinScans", "tr", ContentType.MANGA, false),
	MGKOMIK("MgKomik", "id", ContentType.MANGA, true),
	MHSCANS("MhScans", "es", ContentType.MANGA, false),
	MI2MANGAES("Mi2MangaEs", "es", ContentType.MANGA, false),
	MIAUSCAN("LectorMiau", "es", ContentType.MANGA, false),
	MIHENTAI("MiHentai", "id", ContentType.HENTAI, false),
	MIKOROKU("Mikoroku", "id", ContentType.HENTAI, false),
	MIKROKOSMOSFB("Mikrokosmosfb", "tr", ContentType.HENTAI, false),
	MILASUB("MilaSub", "tr", ContentType.MANGA, true),
	MILFTOON("MilfToon", "en", ContentType.HENTAI, false),
	MIMIHENTAI("MimiHentai", "vi", ContentType.MANGA, false),
	MINDAFANSUB("MindaFansub", "tr", ContentType.HENTAI, false),
	MINITWOSCAN("MiniTwoScan", "pt", ContentType.MANGA, false),
	MINTMANGA("MintManga", "ru", ContentType.MANGA, false),
	MISSKON("MissKon", "type = ContentType.OTHER", ContentType.MANGA, false),
	MMDAOS("Mmdaos", "es", ContentType.MANGA, true),
	MMSCANS("MmScans", "en", ContentType.MANGA, true),
	MODESCANLATOR("ModeScanlator", "pt", ContentType.MANGA, true),
	MOMONOHANASCAN("MomonohanaScan", "pt", ContentType.MANGA, true),
	MONARCAMANGA("MonarcaManga", "es", ContentType.MANGA, true),
	MONZEEKOMIK("MonzeeKomik", "id", ContentType.MANGA, true),
	MOONDAISY_SCANS("MoonDaisyScans", "tr", ContentType.HENTAI, false),
	MOONLOVERSSCAN("MoonLoversScan", "pt", ContentType.HENTAI, false),
	MOONWITCHINLOVESCAN("MoonWitchinScan", "pt", ContentType.MANGA, false),
	MORTALSGROOVE("MortalsGroove", "en", ContentType.MANGA, true),
	MRBENNE("MrBenne", "pt", ContentType.HENTAI, false),
	MSYPUBLISHER("MsyPublisher", "en", ContentType.MANGA, true),
	MUGIMANGA("MugiManga", "tr", ContentType.MANGA, false),
	MUGIWARASOFICIAL("MugiwarasOficial", "pt", ContentType.MANGA, false),
	MUITOHENTAI("MuitoHentai", "pt", ContentType.HENTAI, false),
	MULTPORN("Multporn", "type = ContentType.HENTAI", ContentType.MANGA, false),
	MUNDOHENTAIOFICIAL("MundoHentaiOficial", "pt", ContentType.HENTAI, false),
	MUNDO_MANHWA("MundoManhwa", "es", ContentType.MANGA, false),
	MURIMSCAN("InkReads", "en", ContentType.MANGA, false),
	MYCOMICLIST("MyComicList", "en", ContentType.COMICS, false),
	MYHEROACADEMIASCAN("MyHeroacAdemiaScan", "fr", ContentType.MANGA, false),
	MYREADINGMANGA("MyReadingManga", "type = ContentType.HENTAI", ContentType.MANGA, false),
	MYSHOJO("MyShojo", "en", ContentType.MANGA, false),
	NABISCANS("NabiScans", "tr", ContentType.MANGA, true),
	NATSU("Natsu", "id", ContentType.MANGA, false),
	NEATMANGA("NeatManga", "en", ContentType.MANGA, false),
	NECROSCANS("NecroScans", "en", ContentType.MANGA, false),
	NEKOPOST("NekoPost", "th", ContentType.HENTAI, true),
	NEKOSCANS("NekoScans", "es", ContentType.MANGA, true),
	NEOX_SCANS("NeoxScans", "pt", ContentType.MANGA, true),
	NEROXUS("Neroxus", "pt", ContentType.MANGA, false),
	NETTRUYEN("NetTruyen", "vi", ContentType.MANGA, false),
	NETTRUYEN1975("NetTruyen1975", "vi", ContentType.MANGA, false),
	NETTRUYENFE("NetTruyenFE", "vi", ContentType.MANGA, false),
	NETTRUYENHE("NetTruyenHE", "vi", ContentType.MANGA, false),
	NETTRUYENLL("NetTruyenLL", "vi", ContentType.MANGA, false),
	NETTRUYENSSR("NetTruyenSSR", "vi", ContentType.MANGA, false),
	NETTRUYENUU("NetTruyenUU", "vi", ContentType.MANGA, false),
	NETTRUYENVIE("NetTruyenVie", "vi", ContentType.MANGA, false),
	NETTRUYENX("NetTruyenX", "vi", ContentType.MANGA, true),
	NEUMANGA("NeuManga.xyz", "id", ContentType.MANGA, false),
	NEWMANHUA("NewManhua", "en", ContentType.MANGA, true),
	NEWTRUYEN("NewTruyen", "vi", ContentType.MANGA, false),
	NGAMENKOMIK("NgamenKomik", "id", ContentType.MANGA, false),
	NGOMIK("Ngomik", "id", ContentType.MANGA, false),
	NHATTRUYENVN("NhatTruyenVN", "vi", ContentType.MANGA, false),
	NHENTAI("NHentai.net", "type = ContentType.HENTAI", ContentType.MANGA, false),
	NHENTAIWORLD("Nhentai World", "vi", ContentType.HENTAI, true),
	NHENTAI_TO("NHentai.to", "type = ContentType.HENTAI", ContentType.MANGA, false),
	NHENTAI_XXX("NHentai.xxx", "type = ContentType.HENTAI", ContentType.MANGA, false),
	NICOVIDEO_SEIGA("NicoVideo Seiga", "ja", ContentType.MANGA, false),
	NIGHTCOMIC("Night Comic", "en", ContentType.MANGA, true),
	NIGHTSCANS("NightScans", "en", ContentType.MANGA, false),
	NIJITRANSLATIONS("Niji Translations", "ar", ContentType.MANGA, false),
	NIMEMOB("Nimemob", "id", ContentType.MANGA, true),
	NINEMANGA_BR("NineManga Brasil", "pt", ContentType.MANGA, true),
	NINEMANGA_DE("NineManga Deutsch", "de", ContentType.MANGA, true),
	NINEMANGA_EN("NineManga English", "en", ContentType.MANGA, true),
	NINEMANGA_ES("NineManga Español", "es", ContentType.MANGA, true),
	NINEMANGA_FR("NineManga Français", "fr", ContentType.MANGA, true),
	NINEMANGA_IT("NineManga Italiano", "it", ContentType.MANGA, true),
	NINEMANGA_RU("NineManga Русский", "ru", ContentType.MANGA, true),
	NINENINENINEHENTAI("AnimeH", "type = ContentType.HENTAI", ContentType.MANGA, true),
	NINJASCAN("NinjaComics", "pt", ContentType.MANGA, false),
	NIRVANAMANGA("NirvanaManga", "tr", ContentType.MANGA, false),
	NIRVANASCAN("NirvanaScan", "pt", ContentType.MANGA, false),
	NITROMANGA("NitroManga", "en", ContentType.MANGA, false),
	NIVERAFANSUB("NiveraFansub", "tr", ContentType.HENTAI, false),
	NOBLESSETRANSLATIONS("NoblesseTranslations", "es", ContentType.MANGA, false),
	NOCSUMMER("NocturneSummer", "pt", ContentType.HENTAI, false),
	NOINDEXSCAN("NoindexScan", "pt", ContentType.HENTAI, false),
	NOONSCAN("NoonScan.com", "ar", ContentType.MANGA, true),
	NORMOYUN("MangaSwat", "ar", ContentType.MANGA, true),
	NOROMAX("Noromax", "id", ContentType.MANGA, false),
	NORTEROSE("Norterose", "pt", ContentType.MANGA, false),
	NOVELCROW("NovelCrow", "en", ContentType.HENTAI, false),
	NOVELMIC("NovelMic", "en", ContentType.MANGA, false),
	NOVELSTOWN("NovelsTown", "ar", ContentType.MANGA, true),
	NOXSCANS("NoxScans", "tr", ContentType.MANGA, true),
	NTRMANGA("NtrManga", "th", ContentType.HENTAI, false),
	NUDEMOON("Nude-Moon", "ru", ContentType.MANGA, false),
	NVMANGA("NvManga", "en", ContentType.MANGA, true),
	NYXMANGA("NyxManga", "tr", ContentType.MANGA, true),
	NYXSCANS("Nyx Scans", "en", ContentType.MANGA, false),
	OIOIVN("OioiVn", "vi", ContentType.MANGA, true),
	OKYYKOMIK("OkyyKomik", "id", ContentType.MANGA, false),
	OLAOE("Olaoe", "ar", ContentType.MANGA, false),
	OLIMPOSCANS("OlimpoScans", "es", ContentType.MANGA, false),
	OMEGASCANS("OmegaScans", "en", ContentType.HENTAI, false),
	ONEPIECEEX("OnePieceEx", "pt", ContentType.MANGA, true),
	ONEPIECESCAN("OnePieceScan", "fr", ContentType.MANGA, false),
	ONEPUNCHMANSCAN("OnePunchManScan", "fr", ContentType.MANGA, false),
	ONLYMANHWA("OnlyManhwa", "en", ContentType.MANGA, true),
	ONMA("Onma", "ar", ContentType.MANGA, false),
	OPIATOON("OpiaToon", "tr", ContentType.MANGA, false),
	ORIGAMIORPHEANS("Origami Orpheans", "pt", ContentType.MANGA, false),
	OSHINOKO("OshiNoKo", "fr", ContentType.MANGA, false),
	OTAKUSAN_EN("Otaku Sanctuary (EN)", "en", ContentType.MANGA, true),
	OTAKUSAN_VI("Otaku Sanctuary (VN)", "vi", ContentType.MANGA, true),
	OTRUYEN("Ổ Truyện", "vi", ContentType.MANGA, false),
	OTSUGAMI("Otsugami", "id", ContentType.MANGA, true),
	PANCONCOLA("Panconcola", "es", ContentType.MANGA, true),
	PANTHEONSCAN("PantheonScan.com", "fr", ContentType.MANGA, false),
	PANTHEONSCAN_FR("PantheonScan.fr", "fr", ContentType.MANGA, true),
	PAPSCAN("PapScan", "fr", ContentType.MANGA, true),
	PARITEHABER("Paritehaber", "en", ContentType.HENTAI, false),
	PASSAMAOSCAN("PassamaoScan", "pt", ContentType.MANGA, false),
	PATIMANGA("PatiManga", "tr", ContentType.MANGA, false),
	PAWMANGA("PawManga", "en", ContentType.HENTAI, false),
	PEACHBL("PeachBl", "ar", ContentType.HENTAI, false),
	PERF_SCAN("PerfScan", "fr", ContentType.MANGA, true),
	PETROTECHSOCIETY("Petrotech Society", "en", ContentType.HENTAI, false),
	PHENIXSCANS("PhenixScans", "fr", ContentType.MANGA, true),
	PHILIASCANS("Philia Scans", "en", ContentType.MANGA, false),
	PHOENIXSCANS("PhoenixScans", "it", ContentType.MANGA, false),
	PIANMANGA("PianManga", "en", ContentType.MANGA, true),
	PIEDPIPERFANSUB("PiedpiperFansub", "tr", ContentType.MANGA, false),
	PIEDPIPERFANSUBYY("PiedPiperFansubyy", "tr", ContentType.HENTAI, false),
	PINKTEACOMIC("PinkTeaComic", "vi", ContentType.MANGA, true),
	PIRULITOROSA("PirulitoRosa", "pt", ContentType.HENTAI, false),
	PIXHENTAI("PixHentai", "id", ContentType.HENTAI, false),
	PLATINUMSCANS("PlatinumScans", "en", ContentType.MANGA, false),
	PLUMACOMICS("PlumaComics", "pt", ContentType.MANGA, false),
	PO2SCANS("Po2Scans", "en", ContentType.MANGA, true),
	POINTZEROTOONS("PointZero Toons", "pt", ContentType.MANGA, false),
	POJOKMANGA("PojokManga", "id", ContentType.MANGA, false),
	PONYMANGA("PonyManga", "en", ContentType.HENTAI, true),
	POPSMANGA("PopsManga", "th", ContentType.MANGA, false),
	PORNCOMIC18("18PornComic", "en", ContentType.HENTAI, false),
	PORNCOMIXONLINE("PornComix.online", "en", ContentType.HENTAI, false),
	PORNHWASCANS("PornhwaScans", "fr", ContentType.MANGA, true),
	PORTALYAOI("PortalYaoi", "pt", ContentType.HENTAI, false),
	POSEIDONSCANS("Poseidon Scans", "fr", ContentType.MANGA, true),
	POTATOMANGA("PotatoManga", "ar", ContentType.MANGA, true),
	POWERMANGA("PowerManga", "it", ContentType.MANGA, true),
	PRISMA_HENTAI("PrismaHentai", "pt", ContentType.HENTAI, true),
	PROCHAN("Prochan", "ar", ContentType.MANGA, true),
	PROJECTSUKI("Project Suki", "", ContentType.MANGA, false),
	PROJETOSCANLATOR("ProjetoScanlator", "pt", ContentType.MANGA, true),
	PRUNUSSCANS("PrunusScans", "tr", ContentType.MANGA, true),
	PSUNICORN("PsUnicorn", "pt", ContentType.HENTAI, true),
	PURURIN("Pururin", "en", ContentType.HENTAI, true),
	PUSSYSUSSYTOONS("PussySussyToons", "pt", ContentType.HENTAI, false),
	PZYKOSIS666HFANSUB("Pzykosis666h Fansub", "es", ContentType.HENTAI, false),
	QISCANS("Qi Scans", "en", ContentType.MANGA, false),
	QUAANHDAOCUTEO("Quả Anh Đào Cuteo", "vi", ContentType.HENTAI, false),
	RACKUSREADS("RackusReads", "en", ContentType.MANGA, false),
	RAGNAROKSCAN("RagnarokScan", "es", ContentType.MANGA, true),
	RAGNAROKSCANLATION("RagnarokScanlation", "es", ContentType.MANGA, false),
	RAGNARSCANS("Ragnarscans", "tr", ContentType.MANGA, false),
	RAGNASCAN("RagnaScan", "es", ContentType.MANGA, true),
	RAIJINSCANS("RaijinScans", "fr", ContentType.MANGA, false),
	RAIKISCAN("RaikiScan", "es", ContentType.MANGA, false),
	RAINBOWFAIRYSCAN("RainbowFairyScan", "pt", ContentType.MANGA, true),
	RAINDROPTEAMFAN("Raindrop Fansub", "tr", ContentType.MANGA, false),
	RAISCANS("KenScans", "en", ContentType.MANGA, false),
	RAMAREADER("RamaReader", "it", ContentType.MANGA, false),
	RANDOMSCANS("LuratoonScan", "pt", ContentType.MANGA, true),
	RAVENSCANS("RavenScans", "en", ContentType.MANGA, false),
	RAW1001("Raw1001", "ja", ContentType.MANGA, false),
	RAWDEX("RawDex", "ko", ContentType.HENTAI, false),
	RAWKUMA("Rawkuma", "ja", ContentType.MANGA, false),
	RAWMANGA("RawManga", "ja", ContentType.MANGA, true),
	RAWXZ("RawXz", "ja", ContentType.MANGA, true),
	RAYSSCAN("RaysScan", "pt", ContentType.MANGA, false),
	READCOMICONLINE("ReadComicOnline", "en", ContentType.COMICS, true),
	READCOMICSONLINE("ReadComicsOnline.ru", "en", ContentType.COMICS, false),
	READERGEN("ReaderGen", "fr", ContentType.MANGA, true),
	READERSPOINT("ReadersPoint", "en", ContentType.MANGA, true),
	READER_EVILFLOWERS("EvilFlowers", "en", ContentType.MANGA, false),
	READFREECOMICS("ReadFreeComics", "en", ContentType.MANGA, true),
	READKOMIK("ReadKomik", "en", ContentType.MANGA, false),
	READMANGA_RU("ReadManga", "ru", ContentType.MANGA, false),
	READMANHUA("ReadManhua (Broken)", "en", ContentType.HENTAI, true),
	READNIFTEAM("ReadNifTeam", "it", ContentType.MANGA, false),
	READONEPIECE("ReadOnePiece", "en", ContentType.MANGA, false),
	REAPERCOMICS("ReaperComics", "en", ContentType.MANGA, true),
	REAPERSCANSUNORIGINAL("ReaperScansUnoriginal", "en", ContentType.MANGA, false),
	REAPERSCANS_FR("ReaperScans.fr", "fr", ContentType.MANGA, true),
	REAPERTRANS("ReaperTrans", "th", ContentType.MANGA, false),
	REMANGA("Реманга", "ru", ContentType.MANGA, false),
	REMANGAS("ReMangas", "pt", ContentType.MANGA, true),
	RESETSCANS("Resetscans", "en", ContentType.MANGA, false),
	REVOLUTIONSCANTRAD("RevolutionScantrad", "fr", ContentType.MANGA, true),
	REYUME("ReYume", "id", ContentType.MANGA, false),
	REZOSCANS("RezoScans", "en", ContentType.MANGA, false),
	RHPLUSMANGA("Rh2PlusManga", "th", ContentType.MANGA, true),
	RICHTOSCAN("RichtoScan", "es", ContentType.MANGA, false),
	RIGHTDARKSCAN("RightDarkScan", "es", ContentType.MANGA, true),
	RIMUSCANS("RimuScans", "fr", ContentType.MANGA, true),
	RINKOCOMICS("Rinko Comics", "en", ContentType.COMICS, false),
	RIO2MANGANET("ZinchanManga.mobi", "en", ContentType.MANGA, false),
	RIZZCOMIC("RizzComic", "en", ContentType.MANGA, true),
	ROBINMANGA("RobinManga", "tr", ContentType.MANGA, true),
	ROCKSMANGA("RocksManga", "ar", ContentType.MANGA, false),
	ROGMANGAS("RogMangas", "pt", ContentType.MANGA, true),
	ROKARICOMICS("Rokari Comics", "en", ContentType.MANGA, false),
	ROLIASCAN("Rolia Scan", "en", ContentType.MANGA, false),
	ROMANTIKMANGA("RomantikManga", "tr", ContentType.MANGA, false),
	ROSEVEIL("Roseveil", "id", ContentType.MANGA, false),
	RUAHAPCHANHDAY("Rùa Hấp Chanh Dây", "vi", ContentType.MANGA, false),
	RUYAMANGA("RuyaManga", "tr", ContentType.MANGA, false),
	RYZUKOMIK("Ryzukomik", "id", ContentType.MANGA, false),
	S2MANGA("S2Read", "en", ContentType.MANGA, false),
	SADSCANS("SadScans", "tr", ContentType.MANGA, false),
	SAKAMOTODAYS("SakamotoDays", "fr", ContentType.MANGA, false),
	SAMURAISCAN("SamuraiScan", "es", ContentType.MANGA, false),
	SAPPHIRESCAN("SapphireScan", "es", ContentType.MANGA, false),
	SARCASMSCANS("SarcasmScans", "tr", ContentType.HENTAI, false),
	SASANGEYOU("Sasangeyou", "id", ContentType.MANGA, false),
	SAYHENTAI("SayHentai", "vi", ContentType.HENTAI, false),
	SAYTRUYENHAY("PheTruyen", "vi", ContentType.MANGA, true),
	SCAMBERTRASLATOR("ScamberTraslator", "es", ContentType.MANGA, true),
	SCANBORUTO("ScanBoruto", "fr", ContentType.MANGA, false),
	SCANHENTAI("ScanHentai", "fr", ContentType.HENTAI, true),
	SCANHENTAIMENU("ScanHentai.Menu", "fr", ContentType.HENTAI, false),
	SCANITA("ScanIta.org", "it", ContentType.MANGA, false),
	SCANJUJUTSUKAISEN("ScanJujutsuKaisen", "fr", ContentType.MANGA, false),
	SCANMANGA("ScanManga", "fr", ContentType.MANGA, true),
	SCANMANGAVF_WS("ScanMangaVf.ws", "fr", ContentType.MANGA, true),
	SCANS4U("4uScans", "ar", ContentType.MANGA, false),
	SCANSRAW("AquaScans.com", "en", ContentType.MANGA, true),
	SCANS_MANGAS_ME("ScansMangas.me", "fr", ContentType.MANGA, true),
	SCANTRAD("ScanTrad", "fr", ContentType.MANGA, false),
	SCANTRADUNION("ScantradUnion", "fr", ContentType.MANGA, false),
	SCANTRADVF("Scantrad-Vf", "fr", ContentType.MANGA, true),
	SCANVF("ScanVf", "fr", ContentType.MANGA, false),
	SCANVFORG("ScanVf.org", "fr", ContentType.MANGA, false),
	SCARMANGA("ScarManga", "ar", ContentType.MANGA, true),
	SCYLLACOMICS("ScyllaComics", "en", ContentType.MANGA, false),
	SECTSCANS("SectScans", "en", ContentType.MANGA, false),
	SEIMANGA("SeiManga", "ru", ContentType.MANGA, false),
	SEINAGI("Seinagi", "en", ContentType.MANGA, false),
	SEINAGIADULTO("Seinagi Adulto", "es", ContentType.HENTAI, false),
	SEINEMANGA("SeineManga", "fr", ContentType.MANGA, false),
	SEKAIKOMIK("SekaiKomik", "id", ContentType.MANGA, false),
	SEKTEDOUJIN("SekteDoujin", "id", ContentType.HENTAI, false),
	SEKTEKOMIK("SekteKomik", "id", ContentType.MANGA, false),
	SELFMANGA("SelfManga", "ru", ContentType.MANGA, false),
	SENKURO("Senkuro", "ru", ContentType.MANGA, false),
	SENPAIEDICIONES("SenpaiEdiciones", "es", ContentType.MANGA, true),
	SEREINSCAN("SereinScan", "tr", ContentType.MANGA, false),
	SETSUSCANS("SetsuScans", "en", ContentType.MANGA, false),
	SHADOWCEVIRI("ShadowCeviri", "tr", ContentType.COMICS, false),
	SHADOWMANGAS("ShadowMangas", "es", ContentType.MANGA, true),
	SHADOWXMANGA("ShadowXManga", "ar", ContentType.MANGA, true),
	SHEAKOMIK("SheaKomik", "id", ContentType.MANGA, true),
	SHIBAMANGA("ShibaManga", "en", ContentType.MANGA, false),
	SHIJIESCANS("ShijieScans", "tr", ContentType.MANGA, false),
	SHINIGAMI("Shinigami", "id", ContentType.MANGA, false),
	SHIRAKAMI("Shirakami", "id", ContentType.MANGA, false),
	SHIRO_DOUJIN("ShiroDoujin", "id", ContentType.HENTAI, false),
	SHIYURASUB("ShiyuraSub", "id", ContentType.MANGA, false),
	SHOJOSCANS("ShojoScans", "en", ContentType.MANGA, false),
	SHOOTINGSTARSCANS("Shooting Star Scans", "en", ContentType.MANGA, false),
	SIIKOMIK("SiiKomik", "id", ContentType.MANGA, true),
	SILENCESCAN("SilenceScan", "pt", ContentType.HENTAI, false),
	SINENSISSCANS("SinensisScans", "pt", ContentType.MANGA, true),
	SIRENKOMIK("SirenKomik", "id", ContentType.MANGA, true),
	SITEMANGA("SiteManga", "en", ContentType.MANGA, false),
	SKANLACJEFENIKSY("SkanlacjeFeniksy", "pl", ContentType.MANGA, false),
	SKYMANGAS("SkyMangas", "es", ContentType.MANGA, true),
	SKY_MANGA("SkyManga", "en", ContentType.MANGA, true),
	SLEEPYTRANSLATIONS("Sleepy Translations", "en", ContentType.MANGA, false),
	SNKSCAN("SnkScan", "fr", ContentType.MANGA, false),
	SNOWMACHINETRANSLATION("Snow Machine Translation", "en", ContentType.MANGA, false),
	SNOWMTL("SnowMTL", "en", ContentType.MANGA, true),
	SNOWSCANS("SnowScans", "en", ContentType.MANGA, true),
	SNSCOEURTURKEY("SnscoeurTurkey", "tr", ContentType.HENTAI, false),
	SOBATMANKU("Sobatmanku", "id", ContentType.MANGA, true),
	SODSAIME("สดใสเมะ", "th", ContentType.MANGA, false),
	SOFTKOMIK("Softkomik", "id", ContentType.MANGA, false),
	SOLARMTL("SolarMTL", "en", ContentType.MANGA, true),
	SOLOOSCAN("SolooScan", "pt", ContentType.MANGA, true),
	SOMANGA("SoManga", "th", ContentType.MANGA, true),
	SOULSCANS("SoulScans", "id", ContentType.MANGA, false),
	SPIDERSCANS("SpiderScans", "en", ContentType.MANGA, true),
	SSREADING("SsReading", "pt", ContentType.MANGA, false),
	SSSSCANLATOR("YomuComics", "pt", ContentType.MANGA, true),
	STARBOUNDSCANS("StarboundScans", "fr", ContentType.MANGA, true),
	STELLARSABER("StellarSaber", "ar", ContentType.MANGA, false),
	STICKHORSE("StickHorse", "es", ContentType.MANGA, true),
	STKISSMANGABLOG("1StKissManga.net", "en", ContentType.MANGA, true),
	STKISSMANGA_COM("1stKissManga.com", "en", ContentType.MANGA, true),
	STONESCAPE("StoneScape", "en", ContentType.MANGA, false),
	STRAYFANSUB("StrayFansub", "tr", ContentType.MANGA, true),
	SUMMANGA("SumManga", "en", ContentType.HENTAI, false),
	SUMMERTOON("SummerToon", "tr", ContentType.MANGA, false),
	SURYASCANS("GenzToon", "en", ContentType.MANGA, false),
	SUSHISCAN("SushiScan.Net", "fr", ContentType.MANGA, false),
	SUSHISCANFR("SushiScan.fr", "fr", ContentType.MANGA, false),
	SUSSYSCAN("SussyScan", "pt", ContentType.MANGA, false),
	SWEETSCAN("SweetScan", "pt", ContentType.MANGA, false),
	TANKOUHENTAI("TankouHentai", "pt", ContentType.HENTAI, false),
	TANUKIMANGA("TanukiManga", "th", ContentType.MANGA, false),
	TAROTSCANS("TarotScans", "tr", ContentType.MANGA, false),
	TATAKAE_SCANS("TatakaeScans", "pt", ContentType.MANGA, false),
	TAURUSMANGA("TaurusManga", "es", ContentType.MANGA, false),
	TCBSCANSMANGA("TcbScansManga", "en", ContentType.MANGA, false),
	TEAMXNOVEL("TeamXNovel", "ar", ContentType.MANGA, false),
	TECNOPROJECTS("TecnoProjects", "es", ContentType.MANGA, true),
	TECNOSCANN("TecnoScann", "es", ContentType.MANGA, true),
	TECNOSCANS("TecnoScans", "en", ContentType.MANGA, false),
	TEENMANHUA("TeenManhua", "en", ContentType.MANGA, true),
	TEMAKIMANGAS("TemakiMangas", "pt", ContentType.MANGA, false),
	TEMPESTFANSUB("TempestFansub.Com", "tr", ContentType.MANGA, true),
	TEMPESTFANSUBNET("tempestmangas.com", "tr", ContentType.MANGA, false),
	TEMPESTSCANS("TempestScans", "tr", ContentType.MANGA, false),
	TEMPLESCAN("TempleScan", "en", ContentType.MANGA, true),
	TEMPLESCANESP("TempleScanEsp", "es", ContentType.HENTAI, true),
	TENKAISCAN("TenkaiScan", "es", ContentType.HENTAI, true),
	TENSHIMANGA("Tenshi Manga", "tr", ContentType.MANGA, false),
	TERRITORIOLEAL("TerritorioLeal", "es", ContentType.MANGA, false),
	THAIMANGA("ThaiManga", "th", ContentType.MANGA, false),
	THEGUILDSCANS("TheGuildScans", "en", ContentType.MANGA, true),
	THRIVE("Thrive", "id", ContentType.MANGA, false),
	THUNDERSCANS("ThunderScans", "ar", ContentType.MANGA, false),
	TILKISCANS("TilkiScans", "tr", ContentType.MANGA, false),
	TIMENAIGHT("TimeNaight", "tr", ContentType.MANGA, false),
	TITANMANGA("TitanManga", "tr", ContentType.MANGA, false),
	TMOMANGA("TmoManga", "es", ContentType.MANGA, true),
	TOKYOREVENGERS("TokyoRevengers", "fr", ContentType.MANGA, false),
	TOMILOLIB("TomiloLib", "ru", ContentType.MANGA, false),
	TONIZUTOON("ToniZu.com", "tr", ContentType.HENTAI, false),
	TOOMICS("Toomics", "de", ContentType.MANGA, true),
	TOOMICSDE("TooMicsDe", "de", ContentType.MANGA, false),
	TOOMICSEN("TooMicsEn", "en", ContentType.MANGA, false),
	TOOMICSES("TooMicsEs", "es", ContentType.MANGA, false),
	TOOMICSESLA("TooMicsEsLa", "es", ContentType.MANGA, false),
	TOOMICSFR("TooMicsFr", "fr", ContentType.MANGA, false),
	TOOMICSIT("TooMicsIt", "it", ContentType.MANGA, false),
	TOOMICSJA("TooMicsJa", "ja", ContentType.MANGA, false),
	TOOMICSPT("TooMicsPt", "pt", ContentType.MANGA, false),
	TOOMICSSC("TooMicsSc", "zh", ContentType.MANGA, false),
	TOOMICSTC("TooMicsTc", "zh", ContentType.MANGA, false),
	TOOMTAMMANGA("ToomtamManga", "th", ContentType.HENTAI, false),
	TOONCHILL("ToonChill", "en", ContentType.MANGA, true),
	TOONCUBUS("ToonCubus", "id", ContentType.HENTAI, false),
	TOONFR("ToonFr", "fr", ContentType.HENTAI, false),
	TOONGOD("ToonGod", "en", ContentType.HENTAI, false),
	TOONHUNTER("ToonHunter", "th", ContentType.MANGA, false),
	TOONILY("Toonily", "en", ContentType.MANGA, false),
	TOONILY_ME("Toonily.Me", "en", ContentType.HENTAI, false),
	TOONITUBE("TooniTube", "en", ContentType.HENTAI, false),
	TOONIZY("Toonizy", "en", ContentType.HENTAI, false),
	TOPCOMICPORNO("TopComicPorno", "es", ContentType.HENTAI, false),
	TOPMANHUA("ManhuaTop", "en", ContentType.MANGA, false),
	TOPREADMANHWA("TopReadManhwa", "en", ContentType.MANGA, false),
	TOPTRUYEN("TopTruyen", "vi", ContentType.MANGA, false),
	TORTUGACEVIRI("TortugaCeviri", "tr", ContentType.MANGA, false),
	TRADUCCIONESAMISTOSAS("TraduccionesAmistosas", "es", ContentType.MANGA, false),
	TRADUCCIONESMOONLIGHT("TraduccionesMoonlight", "es", ContentType.HENTAI, false),
	TREE_MANGA("TreeManga", "en", ContentType.MANGA, true),
	TRESDAOS("Tresdaos", "es", ContentType.MANGA, false),
	TRITINIA("Tritinia", "en", ContentType.MANGA, false),
	TRMANGAOKU("TrMangaOku", "tr", ContentType.MANGA, false),
	TRUEMANGA("TrueManga", "en", ContentType.MANGA, true),
	TRUYENGG("FoxTruyen", "vi", ContentType.MANGA, false),
	TRUYENHENTAI18("TruyenHentai18", "vi", ContentType.HENTAI, false),
	TRUYENHENTAIVN("TruyenHentaiVN", "vi", ContentType.MANGA, false),
	TRUYENQQ("TruyenQQ", "vi", ContentType.MANGA, false),
	TRUYENTRANH3Q("TruyenTranh3Q", "vi", ContentType.MANGA, false),
	TRUYENTRANHDAMMYY("Truyện Tranh Đam Mỹ", "vi", ContentType.MANGA, false),
	TRUYENTRANHFULL("Truyện Tranh Full", "vi", ContentType.MANGA, false),
	TRUYENVN("TruyenVn", "vi", ContentType.HENTAI, false),
	TRWEBTOON("TrWebtoon", "tr", ContentType.MANGA, false),
	TSUNDOKU("Tsundoku", "pt", ContentType.MANGA, false),
	TUKANGKOMIK("Tukang Komik", "id", ContentType.MANGA, true),
	TUMANGAONLINE("TuMangaOnline", "es", ContentType.MANGA, false),
	TUMANHWAS("Tumanhwas", "es", ContentType.HENTAI, false),
	TUTTOANIMEMANGA("TuttoAnimeManga", "it", ContentType.MANGA, false),
	TU_MANHWAS("TuManhwas.com", "es", ContentType.MANGA, false),
	TYRANTSCANS("TyrantScans", "pt", ContentType.MANGA, false),
	UKIYOTOON("UkiyoToon", "es", ContentType.MANGA, true),
	ULASCOMIC("UlasComic", "id", ContentType.MANGA, false),
	UMIMANGA("UmiManga", "ar", ContentType.MANGA, false),
	UNIVERSOHENTAI("UniversoHentai", "pt", ContentType.HENTAI, false),
	USAGI("Usagi", "ru", ContentType.MANGA, false),
	UTOON("UToon", "en", ContentType.MANGA, false),
	UZAYMANGA("Uzay Manga", "tr", ContentType.MANGA, true),
	VALKYRIESCAN("ValkyrieScan", "pt", ContentType.HENTAI, false),
	VARNASCAN("VarnaScan", "en", ContentType.MANGA, false),
	VCOMYCS("Vcomycs", "vi", ContentType.MANGA, true),
	VERCOMICSPORNO("VerComicsPorno", "es", ContentType.HENTAI, false),
	VERMANGASPORNO("VerMangasPorno", "es", ContentType.HENTAI, false),
	VERMANHWA("Vermanhwa", "es", ContentType.HENTAI, false),
	VEXMANGA("VexManga", "ar", ContentType.MANGA, true),
	VFSCAN("VfScan", "fr", ContentType.MANGA, true),
	VILLAINESSSCAN("VillainessScan", "pt", ContentType.HENTAI, true),
	VINLANDSAGA("VinlandSaga", "fr", ContentType.MANGA, false),
	VIOLETSCANS("VioletScans", "en", ContentType.MANGA, false),
	VIYAFANSUB("ViyaFansub", "tr", ContentType.HENTAI, true),
	VOIDSCANS("HiveToon", "en", ContentType.MANGA, true),
	VOIDSCANS_CO("VoidScans", "en", ContentType.MANGA, true),
	VORTEXSCANS("VortexScans", "en", ContentType.MANGA, false),
	VYMANGA("VyManga", "en", ContentType.MANGA, false),
	VYVYMANGA("VyvyManga", "en", ContentType.MANGA, true),
	WALPURGISCAN("WalpurgiScan", "it", ContentType.MANGA, false),
	WAMANGA("WaManga", "ru", ContentType.MANGA, false),
	WARUNGKOMIK("WarungKomik", "id", ContentType.MANGA, true),
	WAVETEAMY("Waveteamy", "ar", ContentType.MANGA, false),
	WEBDEXSCANS("WebDexScans", "en", ContentType.MANGA, false),
	WEBTOON("Webtoon.uk", "en", ContentType.MANGA, true),
	WEBTOONEMPIRE("WebtoonEmpire", "ar", ContentType.MANGA, false),
	WEBTOONHATTI("WebtoonHatti", "tr", ContentType.MANGA, false),
	WEBTOONSCAN("WebtoonScan", "en", ContentType.HENTAI, false),
	WEBTOONS_DE("Webtoons German", "de", ContentType.MANGA, false),
	WEBTOONS_EN("Webtoons English", "en", ContentType.MANGA, false),
	WEBTOONS_ES("Webtoons Spanish", "es", ContentType.MANGA, false),
	WEBTOONS_FR("Webtoons French", "fr", ContentType.MANGA, false),
	WEBTOONS_ID("Webtoons Indonesia", "id", ContentType.MANGA, false),
	WEBTOONS_TH("Webtoons Thai", "th", ContentType.MANGA, false),
	WEBTOONS_ZH("Webtoons Chinese", "zh", ContentType.MANGA, false),
	WEBTOONTR("WebtoonTr", "tr", ContentType.MANGA, false),
	WEBTOONXYZ("Webtoon.xyz", "en", ContentType.HENTAI, false),
	WEEBCENTRAL("Weeb Central", "en", ContentType.MANGA, false),
	WEEBDEX_DE("WeebDex (Deutsch)", "de", ContentType.MANGA, false),
	WEEBDEX_EN("WeebDex (English)", "en", ContentType.MANGA, false),
	WEEBDEX_ES("WeebDex (Español)", "es", ContentType.MANGA, false),
	WEEBDEX_FR("WeebDex (Français)", "fr", ContentType.MANGA, false),
	WEEBDEX_IT("WeebDex (Italiano)", "it", ContentType.MANGA, false),
	WEEBDEX_JA("WeebDex (日本語)", "ja", ContentType.MANGA, false),
	WEEBDEX_KO("WeebDex (한국어)", "ko", ContentType.MANGA, false),
	WEEBDEX_PT("WeebDex (Português)", "pt", ContentType.MANGA, false),
	WEEBDEX_RU("WeebDex (Русский)", "ru", ContentType.MANGA, false),
	WEEBDEX_ZH("WeebDex (中文)", "zh", ContentType.MANGA, false),
	WELOMA("Weloma", "ja", ContentType.MANGA, false),
	WELOVEMANGA("WeLoveManga", "ja", ContentType.MANGA, false),
	WESTMANGA("WestManga", "id", ContentType.MANGA, false),
	WHALEMANGA("WhaleManga", "en", ContentType.MANGA, false),
	WICKEDWITCHSCAN("WickedWitchScan", "pt", ContentType.MANGA, false),
	WINTERSCAN("WinterScan", "pt", ContentType.MANGA, false),
	WITCHSCANS("WitchScans", "en", ContentType.MANGA, false),
	WITCOMICS("WitComics", "it", ContentType.MANGA, true),
	WOLFSCANBR("WolfScanBr", "pt", ContentType.MANGA, false),
	WONDERLANDSCAN("WonderlandScan", "pt", ContentType.MANGA, false),
	WOOPREAD("Woopread", "en", ContentType.MANGA, false),
	WORLDMANHWAS("WorldManhwas", "id", ContentType.HENTAI, true),
	XBATCAT("XBatCat", "", ContentType.MANGA, true),
	XCALIBRSCANS("XCalibrScans", "en", ContentType.MANGA, false),
	XIUTAKU("Xiutaku", "zh", ContentType.MANGA, false),
	XMANHWA("XManhwa", "id", ContentType.HENTAI, false),
	XOXOCOMICS("XoxoComics", "en", ContentType.COMICS, false),
	XSANOMANGA("XsanoManga", "ar", ContentType.MANGA, false),
	XSSCAN("XsScan", "pt", ContentType.MANGA, false),
	XXXREVOLUTIONSCANTRAD("Xxx.RevolutionScantrad", "fr", ContentType.HENTAI, true),
	YAKSHACOMICS("YakshaComics", "en", ContentType.MANGA, false),
	YANPFANSUB("YanpFansub", "pt", ContentType.MANGA, false),
	YAOIBAR("YaoiBar", "tr", ContentType.MANGA, false),
	YAOICHAN("Яой-тян", "ru", ContentType.MANGA, false),
	YAOIFANCLUB("YaoiFanClub", "pt", ContentType.MANGA, false),
	YAOIFLIX("YaoiFlix", "tr", ContentType.HENTAI, false),
	YAOIHUB("YaoiHub", "en", ContentType.HENTAI, false),
	YAOILIB("SlashLib", "ru", ContentType.MANGA, false),
	YAOIMANGA("YaoiManga", "es", ContentType.MANGA, false),
	YAOIMANGAOKU("YaoiMangaOku", "tr", ContentType.HENTAI, false),
	YAOIMANGAONLINE("YaoiMangaOnline", "en", ContentType.HENTAI, false),
	YAOIMOBI("Yaoi.Mobi", "en", ContentType.HENTAI, true),
	YAOISCAN("YaoiScan", "en", ContentType.HENTAI, false),
	YAOITR("YaoiTr", "tr", ContentType.MANGA, true),
	YAOIX3("3XYaoi", "pt", ContentType.HENTAI, false),
	YCSCAN("YcScan", "pt", ContentType.HENTAI, false),
	YDCOMICS("YdComics", "en", ContentType.MANGA, true),
	YETISKINRUYAMANGA("Yetişkin Rüya Manga", "tr", ContentType.MANGA, true),
	YKMH("Ykmh", "zh", ContentType.MANGA, false),
	YOKAITEAM("YokaiTeam", "ar", ContentType.MANGA, false),
	YOMUMANGAS("Yomu Mangas", "pt", ContentType.MANGA, false),
	YONABAR("YonaBar", "ar", ContentType.MANGA, false),
	YUBIKIRI("Yubikiri", "id", ContentType.MANGA, true),
	YUGENMANGAS("YugenApp", "pt", ContentType.MANGA, false),
	YUGEN_MANGAS_ES("YugenMangas.lat", "es", ContentType.HENTAI, true),
	YUMEKOMIK("YumeKomik", "id", ContentType.MANGA, true),
	YURAMANGA("YuraManga", "id", ContentType.MANGA, true),
	YURIBASE("YuriBase", "id", ContentType.MANGA, false),
	YURIGARDEN("Yuri Garden", "vi", ContentType.MANGA, false),
	YURIGARDEN_R18("Yuri Garden (18+)", "vi", ContentType.MANGA, false),
	YURILAB("YuriLab", "id", ContentType.HENTAI, true),
	YURILIVE("YuriLive", "pt", ContentType.HENTAI, false),
	YURIMOONSUB("Yurimoonsub.blogspot.com", "ar", ContentType.MANGA, false),
	YURINEKO("YuriNeko", "vi", ContentType.HENTAI, true),
	ZAHARD("Zahard", "en", ContentType.MANGA, true),
	ZAMANMANGA("ZamanManga", "tr", ContentType.MANGA, true),
	ZANDYNOFANSUB("Zandyno Fansub", "en", ContentType.MANGA, false),
	ZENITHSCANS("ZenithScans", "tr", ContentType.MANGA, false),
	ZENMANGA("ZenManga", "ru", ContentType.MANGA, true),
	ZEVEP("Zevep", "es", ContentType.MANGA, true),
	ZINCHANMANGA("ZinChanManga.Com", "en", ContentType.HENTAI, false),
	ZINCHANMANGA_NET("ZinchanManga.net", "en", ContentType.MANGA, false),
	ZINMANGA("ZinManga.net", "en", ContentType.MANGA, false),
	ZINMANGA_CC("ZinManga.cc", "en", ContentType.MANGA, true),
	ZINMANGA_MS("ZinManga.ms", "en", ContentType.MANGA, true),
	ZIN_MANGA_COM("Zin-Manga.com", "en", ContentType.MANGA, false),
	ZSCANLATION("ZScanlation", "pt", ContentType.HENTAI, true),
	;
}
